export type workExp = {
  workStart: Date; // начало работы
  workEnd: Date; // конец работы
  companyName: string; // название компании
  position: string; // должность
  resp: string; // обязанности
};

export type applicant = {
  firstName: string; // имя
  lastName: string; // фамилия
  avatar: string; // ссылка на аватар в формате url
  isWinner: boolean; // победитель хакатона?
  city: string; // город
  age: number; // возраст
  responses: number; // длина массива откликов
  completedTestTasks: number; // длина массива тестовых
  interviews: number; // длина массива собеседований
  course: string; // название оконченного курса
  graduationDate: Date; // дата окончания (строка формата 'апрель 2023')
  workFormat: string; // формат работы
  // добавила новые поля
  grade: string; // грейд
  salary: number; // зп
  contacts: string; // контакты
  about: string; // о себе
  workExpirience: Array<workExp>; // массив из объектов мест работы

  // добавила еще поля
  studyingStatus: string; // учебный статус
  responseStatus: string; // статус отклика
  workStatus: string; // опыт работы
};

export type applicantsList = Array<applicant>;
const date: Date = new Date();

const exp1: workExp = {
  workStart: date,
  workEnd: date,
  companyName: "Яндекс",
  position: "Frontent-разработчик",
  resp: `Проект на Web 3.0. Разработал интерфейс администратора для работы с крипто-кошельком и смарт-контрактом. Мониторинг статистики (построение графиков), управление доступами пользователей, вывод средств, арбитражные переводы. Настроил окружение для разработки: ESLint, Prettier, Husky. Внедрил архитектуру FSD в проект, рефакторинг, код ревью, разработал UI-kit c настроенным Storybook,
  Стек: React, Typescript, React-router-dom, Wagmi, Luxon, classnames, Redux-toolkit, Vite, MetaMask , ESLint, Prettier, Husky, Storybook.
  
  Проект "Караоке". Построение приложения с нуля, проектирование архитектуры, сбор требований, текстовые анимации, разработка Ui кит, код ревью, улучшение качества кода коллег, настройка рабочего окружения.
  Стэк: React, Typescript, classnames, Webpack, react-use-audio-player, Zustand, ESLint, Prettier, Husky, FSD, Sass.
  
  Проект "Мерчант" и интефейс платежа. Построение приложения с нуля, проектирование архитектуры, сбор требований, разработка Ui кит (сложные таблицы), код ревью, наставничество, настройка рабочего окружения.
  Стэк: React, Typescript, classnames, Webpack, React-Query ESLint, Prettier, Husky, FSD, Sass.`,
};

const exp2: workExp = {
  workStart: date,
  workEnd: date,
  companyName: "Apple",
  position: "Веб-дизайнер",
  resp: `Я веб-дизайнер на Фрилансе, создаю дизайн сайтов в Figma и Adobe Photoshop , затем выполняю верстку на Тильде. Работаю в зеро блоке, настраиваю анимацию и step by step анимацию. Так же подключаю домен, выполняю базовые настройки seo`,
};

const exp3: workExp = {
  workStart: date,
  workEnd: date,
  companyName: "Google",
  position: "Веб-разработчик",
  resp: `Работа над различными проектами, в частности разработка (доработка) REST API (дополнение функционала, как результата повышение ценности продукта для заказчика), документирование кода, разработка тестов, создание микросервисов "с нуля" (проект интернет-магазина, разработка REST API, внедрение JWT) и другое.`,
};

export const applicants: applicantsList = [
  {
    firstName: "Judah",
    lastName: "Waters",
    avatar: "https://random.imagecdn.app/200/200",
    isWinner: false,
    city: "Lipetsk",
    age: 33,
    responses: 7,
    completedTestTasks: 0,
    interviews: 16,
    course: "Веб-дизайнер",
    graduationDate: date,
    workFormat: "офис",
    grade: "Junior",
    salary: 50000,
    contacts: "+7(813)255-44-44",
    about:
      "Что разум человека может постигнуть и во что он может поверить, того он способен достичь",
    workExpirience: [exp1, exp2, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Venus",
    lastName: "Tate",
    avatar: "https://random.imagecdn.app/200/200",
    isWinner: true,
    city: "Sakhalin",
    age: 35,
    responses: 23,
    completedTestTasks: 3,
    interviews: 23,
    course: "Разработчик C++",
    graduationDate: date,
    workFormat: "удаленный",
    grade: "middle",
    salary: 60000,
    contacts: "+7(918)371-87-25",
    about:
      "Что разум человека может постигнуть и во что он может поверить, того он способен достичь",
    workExpirience: [exp3, exp1, exp2],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Francis",
    lastName: "Swanson",
    avatar: "https://random.imagecdn.app/200/200",
    isWinner: true,
    city: "Novosibirsk",
    age: 32,
    responses: 31,
    completedTestTasks: 8,
    interviews: 18,
    course: "Java-разработчик",
    graduationDate: date,
    workFormat: "офис",
    grade: "Junior",
    salary: 45000,
    contacts: "+7(482)609-48-74",
    about: "Стремитесь не к успеху, а к ценностям, которые он дает",
    workExpirience: [exp2, exp1, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Кандидат",
  },
  {
    firstName: "Seth",
    lastName: "Underwood",
    avatar: "https://random.imagecdn.app/200/200",
    isWinner: false,
    city: "Ryazan",
    age: 18,
    responses: 32,
    completedTestTasks: 8,
    interviews: 10,
    course: "Python-разработчик плюс",
    graduationDate: date,
    workFormat: "удаленный",
    grade: "middle",
    salary: 40000,
    contacts: "+7(592)574-76-41",
    about: "Стремитесь не к успеху, а к ценностям, которые он дает",
    workExpirience: [exp2, exp3, exp1],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Кандидат",
  },
  {
    firstName: "Cruz",
    lastName: "Whitaker",
    avatar: "https://random.imagecdn.app/200/200",
    isWinner: true,
    city: "Ulyanovsk",
    age: 34,
    responses: 24,
    completedTestTasks: 8,
    interviews: 28,
    course: "Фронтенд-разработчик",
    graduationDate: date,
    workFormat: "офис",
    grade: "Junior",
    salary: 55000,
    contacts: "+7(994)498-21-00",
    about: "Я ничьих мнений не разделяю; я имею свои.",
    workExpirience: [exp1, exp2, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Yvonne",
    lastName: "Wade",
    avatar: "https://random.imagecdn.app/200/200",
    isWinner: false,
    city: "Skovorodino",
    age: 55,
    responses: 32,
    completedTestTasks: 2,
    interviews: 7,
    course: "Cтарт в IT",
    graduationDate: date,
    workFormat: "удаленный",
    grade: "middle",
    salary: 90000,
    contacts: "+7(363)550-64-08",
    about: "Я ничьих мнений не разделяю; я имею свои.",
    workExpirience: [exp3, exp1, exp2],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Кандидат",
  },
  {
    firstName: "Stella",
    lastName: "Edwards",
    avatar: "https://random.imagecdn.app/200/200",
    isWinner: true,
    city: "Sakhalin",
    age: 45,
    responses: 5,
    completedTestTasks: 8,
    interviews: 28,
    course: "Системный аналитик",
    graduationDate: date,
    workFormat: "офис",
    grade: "Junior",
    salary: 50000,
    contacts: "+7(165)789-33-61",
    about:
      "За свою карьеру я пропустил более 9000 бросков, проиграл почти 300 игр. 26 раз мне доверяли сделать финальный победный бросок, и я промахивался. Я терпел поражения снова, и снова, и снова. И именно поэтому я добился успеха.",
    workExpirience: [exp2, exp1, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Nolan",
    lastName: "Sosa",
    avatar: "https://random.imagecdn.app/200/200",
    isWinner: false,
    city: "Moscow",
    age: 19,
    responses: 8,
    completedTestTasks: 4,
    interviews: 26,
    course: "Специалист по Data Science плюс",
    graduationDate: date,
    workFormat: "удаленный",
    grade: "middle",
    salary: 60000,
    contacts: "+7(145)398-73-36",
    about:
      "За свою карьеру я пропустил более 9000 бросков, проиграл почти 300 игр. 26 раз мне доверяли сделать финальный победный бросок, и я промахивался. Я терпел поражения снова, и снова, и снова. И именно поэтому я добился успеха.",
    workExpirience: [exp2, exp3, exp1],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Кандидат",
  },
  {
    firstName: "Aretha",
    lastName: "Grimes",
    avatar: "https://random.imagecdn.app/200/200",
    isWinner: true,
    city: "Magadan",
    age: 35,
    responses: 21,
    completedTestTasks: 7,
    interviews: 11,
    course: "Графический дизайнер",
    graduationDate: date,
    workFormat: "офис",
    grade: "Junior",
    salary: 45000,
    contacts: "+7(171)000-14-59",
    about:
      "Через 20 лет вы будете больше разочарованы теми вещами, которые вы не делали, чем теми, которые вы сделали. Так отчальте от тихой пристани. Почувствуйте попутный ветер в вашем парусе. Двигайтесь вперед, действуйте, открывайте!",
    workExpirience: [exp1, exp2, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Кандидат",
  },
  {
    firstName: "Joan",
    lastName: "Hall",
    avatar: "https://random.imagecdn.app/200/200",
    isWinner: false,
    city: "Vologda",
    age: 31,
    responses: 32,
    completedTestTasks: 9,
    interviews: 1,
    course: "iOS-разработчик",
    graduationDate: date,
    workFormat: "удаленный",
    grade: "middle",
    salary: 40000,
    contacts: "+7(654)850-57-39",
    about:
      "Через 20 лет вы будете больше разочарованы теми вещами, которые вы не делали, чем теми, которые вы сделали. Так отчальте от тихой пристани. Почувствуйте попутный ветер в вашем парусе. Двигайтесь вперед, действуйте, открывайте!",
    workExpirience: [exp3, exp1, exp2],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Кандидат",
  },
  {
    firstName: "Uriel",
    lastName: "Guerrero",
    avatar: "https://random.imagecdn.app/200/200",
    isWinner: true,
    city: "Nizhny",
    age: 24,
    responses: 14,
    completedTestTasks: 10,
    interviews: 5,
    course: "Android-разработчик",
    graduationDate: date,
    workFormat: "офис",
    grade: "Junior",
    salary: 55000,
    contacts: "+7(232)536-51-36",
    about:
      "Что-то недоброе таится в мужчинах, избегающих вина, игр, общества прелестных женщин, застольной беседы. Такие люди или тяжело больны, или втайне ненавидят окружающих. Правда, возможны исключения.",
    workExpirience: [exp2, exp1, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Brenna",
    lastName: "Mcpherson",
    avatar: "https://random.imagecdn.app/200/200",
    isWinner: false,
    city: "Kaluga",
    age: 49,
    responses: 14,
    completedTestTasks: 5,
    interviews: 22,
    course: "Веб-дизайнер",
    graduationDate: date,
    workFormat: "удаленный",
    grade: "middle",
    salary: 90000,
    contacts: "+7(823)261-11-33",
    about:
      "Что-то недоброе таится в мужчинах, избегающих вина, игр, общества прелестных женщин, застольной беседы. Такие люди или тяжело больны, или втайне ненавидят окружающих. Правда, возможны исключения.",
    workExpirience: [exp2, exp3, exp1],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Кандидат",
  },
  {
    firstName: "Ryan",
    lastName: "Frazier",
    avatar: "https://random.imagecdn.app/200/200",
    isWinner: false,
    city: "Kurgan",
    age: 51,
    responses: 29,
    completedTestTasks: 4,
    interviews: 25,
    course: "Веб-дизайнер",
    graduationDate: date,
    workFormat: "офис",
    grade: "Junior",
    salary: 50000,
    contacts: "+7(153)351-73-57",
    about:
      "Я помню чудное мгновенье: Передо мной явилась ты, Как мимолетное виденье, Как гений чистой красоты.",
    workExpirience: [exp1, exp2, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Кандидат",
  },
  {
    firstName: "Indira",
    lastName: "Huffman",
    avatar: "https://random.imagecdn.app/200/200",
    isWinner: false,
    city: "Orenburg",
    age: 40,
    responses: 30,
    completedTestTasks: 8,
    interviews: 31,
    course: "Разработчик C++",
    graduationDate: date,
    workFormat: "удаленный",
    grade: "middle",
    salary: 60000,
    contacts: "+7(676)756-21-56",
    about:
      "Я помню чудное мгновенье: Передо мной явилась ты, Как мимолетное виденье, Как гений чистой красоты.",
    workExpirience: [exp3, exp1, exp2],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Кандидат",
  },
  {
    firstName: "Clarke",
    lastName: "Rodriquez",
    avatar: "https://random.imagecdn.app/200/200",
    isWinner: false,
    city: "Tula",
    age: 40,
    responses: 16,
    completedTestTasks: 8,
    interviews: 4,
    course: "Java-разработчик",
    graduationDate: date,
    workFormat: "офис",
    grade: "Junior",
    salary: 45000,
    contacts: "+7(665)832-65-83",
    about:
      "Что разум человека может постигнуть и во что он может поверить, того он способен достичь",
    workExpirience: [exp2, exp1, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Кандидат",
  },
  {
    firstName: "Selma",
    lastName: "Mitchell",
    avatar: "https://random.imagecdn.app/200/200",
    isWinner: true,
    city: "Kaliningrad",
    age: 53,
    responses: 28,
    completedTestTasks: 10,
    interviews: 16,
    course: "Python-разработчик плюс",
    graduationDate: date,
    workFormat: "удаленный",
    grade: "middle",
    salary: 40000,
    contacts: "+7(523)302-72-59",
    about:
      "Что разум человека может постигнуть и во что он может поверить, того он способен достичь",
    workExpirience: [exp2, exp3, exp1],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Кандидат",
  },
  {
    firstName: "Ralph",
    lastName: "Vaughan",
    avatar: "https://random.imagecdn.app/200/200",
    isWinner: true,
    city: "Sakhalin",
    age: 45,
    responses: 3,
    completedTestTasks: 9,
    interviews: 21,
    course: "Фронтенд-разработчик",
    graduationDate: date,
    workFormat: "офис",
    grade: "Junior",
    salary: 55000,
    contacts: "+7(241)697-36-69",
    about: "Стремитесь не к успеху, а к ценностям, которые он дает",
    workExpirience: [exp1, exp2, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Кандидат",
  },
  {
    firstName: "Galvin",
    lastName: "Peck",
    avatar: "https://random.imagecdn.app/200/200",
    isWinner: true,
    city: "Kursk",
    age: 37,
    responses: 28,
    completedTestTasks: 6,
    interviews: 13,
    course: "Cтарт в IT",
    graduationDate: date,
    workFormat: "удаленный",
    grade: "middle",
    salary: 90000,
    contacts: "+7(792)665-06-78",
    about: "Стремитесь не к успеху, а к ценностям, которые он дает",
    workExpirience: [exp3, exp1, exp2],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Кандидат",
  },
  {
    firstName: "Gannon",
    lastName: "Freeman",
    avatar: "https://random.imagecdn.app/200/200",
    isWinner: false,
    city: "Samara",
    age: 55,
    responses: 21,
    completedTestTasks: 2,
    interviews: 2,
    course: "Системный аналитик",
    graduationDate: date,
    workFormat: "офис",
    grade: "Junior",
    salary: 50000,
    contacts: "+7(496)214-41-24",
    about: "Я ничьих мнений не разделяю; я имею свои.",
    workExpirience: [exp2, exp1, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Кандидат",
  },
  {
    firstName: "Yeo",
    lastName: "Willis",
    avatar: "https://random.imagecdn.app/200/200",
    isWinner: false,
    city: "Orenburg",
    age: 54,
    responses: 2,
    completedTestTasks: 6,
    interviews: 33,
    course: "Специалист по Data Science плюс",
    graduationDate: date,
    workFormat: "удаленный",
    grade: "middle",
    salary: 60000,
    contacts: "+7(146)865-17-04",
    about: "Я ничьих мнений не разделяю; я имею свои.",
    workExpirience: [exp2, exp3, exp1],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Кандидат",
  },
  {
    firstName: "Tara",
    lastName: "Morales",
    avatar: "https://random.imagecdn.app/200/200",
    isWinner: true,
    city: "Ryazan",
    age: 19,
    responses: 16,
    completedTestTasks: 2,
    interviews: 26,
    course: "Графический дизайнер",
    graduationDate: date,
    workFormat: "офис",
    grade: "Junior",
    salary: 45000,
    contacts: "+7(281)768-32-32",
    about:
      "За свою карьеру я пропустил более 9000 бросков, проиграл почти 300 игр. 26 раз мне доверяли сделать финальный победный бросок, и я промахивался. Я терпел поражения снова, и снова, и снова. И именно поэтому я добился успеха.",
    workExpirience: [exp1, exp2, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Кандидат",
  },
  {
    firstName: "Martena",
    lastName: "Wright",
    avatar: "https://random.imagecdn.app/200/200",
    isWinner: false,
    city: "Ivanovo",
    age: 51,
    responses: 13,
    completedTestTasks: 3,
    interviews: 17,
    course: "iOS-разработчик",
    graduationDate: date,
    workFormat: "удаленный",
    grade: "middle",
    salary: 40000,
    contacts: "+7(847)376-46-34",
    about:
      "За свою карьеру я пропустил более 9000 бросков, проиграл почти 300 игр. 26 раз мне доверяли сделать финальный победный бросок, и я промахивался. Я терпел поражения снова, и снова, и снова. И именно поэтому я добился успеха.",
    workExpirience: [exp3, exp1, exp2],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Кандидат",
  },
  {
    firstName: "Georgia",
    lastName: "Garner",
    avatar: "https://random.imagecdn.app/200/200",
    isWinner: true,
    city: "Yekaterinburg",
    age: 27,
    responses: 29,
    completedTestTasks: 6,
    interviews: 15,
    course: "Android-разработчик",
    graduationDate: date,
    workFormat: "офис",
    grade: "Junior",
    salary: 55000,
    contacts: "+7(245)481-05-52",
    about:
      "Через 20 лет вы будете больше разочарованы теми вещами, которые вы не делали, чем теми, которые вы сделали. Так отчальте от тихой пристани. Почувствуйте попутный ветер в вашем парусе. Двигайтесь вперед, действуйте, открывайте!",
    workExpirience: [exp2, exp1, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Кандидат",
  },
  {
    firstName: "Lilah",
    lastName: "Andrews",
    avatar: "https://random.imagecdn.app/200/200",
    isWinner: true,
    city: "Novgorod",
    age: 54,
    responses: 27,
    completedTestTasks: 8,
    interviews: 29,
    course: "Веб-дизайнер",
    graduationDate: date,
    workFormat: "удаленный",
    grade: "middle",
    salary: 90000,
    contacts: "+7(864)831-67-25",
    about:
      "Через 20 лет вы будете больше разочарованы теми вещами, которые вы не делали, чем теми, которые вы сделали. Так отчальте от тихой пристани. Почувствуйте попутный ветер в вашем парусе. Двигайтесь вперед, действуйте, открывайте!",
    workExpirience: [exp2, exp3, exp1],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Кандидат",
  },
  {
    firstName: "Laura",
    lastName: "Washington",
    avatar: "https://random.imagecdn.app/200/200",
    isWinner: true,
    city: "Oryol",
    age: 53,
    responses: 3,
    completedTestTasks: 9,
    interviews: 2,
    course: "Веб-дизайнер",
    graduationDate: date,
    workFormat: "офис",
    grade: "Junior",
    salary: 50000,
    contacts: "+7(863)680-23-11",
    about:
      "Что-то недоброе таится в мужчинах, избегающих вина, игр, общества прелестных женщин, застольной беседы. Такие люди или тяжело больны, или втайне ненавидят окружающих. Правда, возможны исключения.",
    workExpirience: [exp1, exp2, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Кандидат",
  },
  {
    firstName: "Darryl",
    lastName: "Johns",
    avatar: "https://random.imagecdn.app/200/200",
    isWinner: true,
    city: "Omsk",
    age: 22,
    responses: 6,
    completedTestTasks: 4,
    interviews: 5,
    course: "Разработчик C++",
    graduationDate: date,
    workFormat: "удаленный",
    grade: "middle",
    salary: 60000,
    contacts: "+7(653)660-46-89",
    about:
      "Что-то недоброе таится в мужчинах, избегающих вина, игр, общества прелестных женщин, застольной беседы. Такие люди или тяжело больны, или втайне ненавидят окружающих. Правда, возможны исключения.",
    workExpirience: [exp3, exp1, exp2],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Кандидат",
  },
  {
    firstName: "Laurel",
    lastName: "Kerr",
    avatar: "https://random.imagecdn.app/200/200",
    isWinner: false,
    city: "Tula",
    age: 48,
    responses: 6,
    completedTestTasks: 2,
    interviews: 31,
    course: "Java-разработчик",
    graduationDate: date,
    workFormat: "офис",
    grade: "Junior",
    salary: 45000,
    contacts: "+7(670)998-36-25",
    about:
      "Я помню чудное мгновенье: Передо мной явилась ты, Как мимолетное виденье, Как гений чистой красоты.",
    workExpirience: [exp2, exp1, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Кандидат",
  },
  {
    firstName: "Axel",
    lastName: "Key",
    avatar: "https://random.imagecdn.app/200/200",
    isWinner: false,
    city: "Surazh",
    age: 53,
    responses: 31,
    completedTestTasks: 3,
    interviews: 22,
    course: "Python-разработчик плюс",
    graduationDate: date,
    workFormat: "удаленный",
    grade: "middle",
    salary: 40000,
    contacts: "+7(815)012-95-21",
    about:
      "Я помню чудное мгновенье: Передо мной явилась ты, Как мимолетное виденье, Как гений чистой красоты.",
    workExpirience: [exp2, exp3, exp1],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Кандидат",
  },
  // {
  // 	"firstName": "Jordan",
  // 	"lastName": "Barrera",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Kartaly",
  // 	"age": 21,
  // 	"responses": 26,
  // 	"completedTestTasks": 6,
  // 	"interviews": 24,
  // 	"course": "Фронтенд-разработчик",
  // 	"graduationDate": "Nov 2022",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 55000,
  // 	"contacts": "+7(381)323-88-29",
  // 	"about": "Что разум человека может постигнуть и во что он может поверить, того он способен достичь",
  // 	"workExpirience": [exp1, exp2, exp3]
  // },
  // {
  // 	"firstName": "Micah",
  // 	"lastName": "Sims",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Zhukovka",
  // 	"age": 22,
  // 	"responses": 32,
  // 	"completedTestTasks": 6,
  // 	"interviews": 5,
  // 	"course": "Cтарт в IT",
  // 	"graduationDate": "Sep 2024",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 90000,
  // 	"contacts": "+7(831)572-33-86",
  // 	"about": "Что разум человека может постигнуть и во что он может поверить, того он способен достичь",
  // 	"workExpirience": [exp3, exp1, exp2]
  // },
  // {
  // 	"firstName": "Fulton",
  // 	"lastName": "Stanton",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Lipetsk",
  // 	"age": 50,
  // 	"responses": 3,
  // 	"completedTestTasks": 7,
  // 	"interviews": 24,
  // 	"course": "Системный аналитик",
  // 	"graduationDate": "Aug 2024",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 50000,
  // 	"contacts": "+7(927)795-69-89",
  // 	"about": "Стремитесь не к успеху, а к ценностям, которые он дает",
  // 	"workExpirience": [exp2, exp1, exp3]
  // },
  // {
  // 	"firstName": "Deanna",
  // 	"lastName": "Pierce",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Kirov",
  // 	"age": 56,
  // 	"responses": 21,
  // 	"completedTestTasks": 8,
  // 	"interviews": 1,
  // 	"course": "Специалист по Data Science плюс",
  // 	"graduationDate": "Aug 2024",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 60000,
  // 	"contacts": "+7(625)573-13-04",
  // 	"about": "Стремитесь не к успеху, а к ценностям, которые он дает",
  // 	"workExpirience": [exp2, exp3, exp1]
  // },
  // {
  // 	"firstName": "Raymond",
  // 	"lastName": "Owens",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Saint Petersburg",
  // 	"age": 41,
  // 	"responses": 24,
  // 	"completedTestTasks": 6,
  // 	"interviews": 5,
  // 	"course": "Графический дизайнер",
  // 	"graduationDate": "Mar 2023",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 45000,
  // 	"contacts": "+7(124)555-20-45",
  // 	"about": "Я ничьих мнений не разделяю; я имею свои.",
  // 	"workExpirience": [exp1, exp2, exp3]
  // },
  // {
  // 	"firstName": "Shad",
  // 	"lastName": "Boyd",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Vladimir",
  // 	"age": 20,
  // 	"responses": 2,
  // 	"completedTestTasks": 3,
  // 	"interviews": 28,
  // 	"course": "iOS-разработчик",
  // 	"graduationDate": "Aug 2024",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 40000,
  // 	"contacts": "+7(683)743-66-72",
  // 	"about": "Я ничьих мнений не разделяю; я имею свои.",
  // 	"workExpirience": [exp3, exp1, exp2]
  // },
  // {
  // 	"firstName": "Jerome",
  // 	"lastName": "Reed",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Tyumen",
  // 	"age": 20,
  // 	"responses": 24,
  // 	"completedTestTasks": 10,
  // 	"interviews": 16,
  // 	"course": "Android-разработчик",
  // 	"graduationDate": "Dec 2023",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 55000,
  // 	"contacts": "+7(912)273-86-36",
  // 	"about": "За свою карьеру я пропустил более 9000 бросков, проиграл почти 300 игр. 26 раз мне доверяли сделать финальный победный бросок, и я промахивался. Я терпел поражения снова, и снова, и снова. И именно поэтому я добился успеха.",
  // 	"workExpirience": [exp2, exp1, exp3]
  // },
  // {
  // 	"firstName": "Daryl",
  // 	"lastName": "Booker",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Shenkursk",
  // 	"age": 42,
  // 	"responses": 15,
  // 	"completedTestTasks": 4,
  // 	"interviews": 17,
  // 	"course": "Веб-дизайнер",
  // 	"graduationDate": "Dec 2022",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 90000,
  // 	"contacts": "+7(548)885-78-27",
  // 	"about": "За свою карьеру я пропустил более 9000 бросков, проиграл почти 300 игр. 26 раз мне доверяли сделать финальный победный бросок, и я промахивался. Я терпел поражения снова, и снова, и снова. И именно поэтому я добился успеха.",
  // 	"workExpirience": [exp2, exp3, exp1]
  // },
  // {
  // 	"firstName": "Peter",
  // 	"lastName": "Glenn",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Saint Petersburg",
  // 	"age": 46,
  // 	"responses": 15,
  // 	"completedTestTasks": 4,
  // 	"interviews": 4,
  // 	"course": "Веб-дизайнер",
  // 	"graduationDate": "Mar 2024",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 50000,
  // 	"contacts": "+7(516)552-07-60",
  // 	"about": "Через 20 лет вы будете больше разочарованы теми вещами, которые вы не делали, чем теми, которые вы сделали. Так отчальте от тихой пристани. Почувствуйте попутный ветер в вашем парусе. Двигайтесь вперед, действуйте, открывайте!",
  // 	"workExpirience": [exp1, exp2, exp3]
  // },
  // {
  // 	"firstName": "Sage",
  // 	"lastName": "Burris",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Tambov",
  // 	"age": 41,
  // 	"responses": 21,
  // 	"completedTestTasks": 7,
  // 	"interviews": 9,
  // 	"course": "Разработчик C++",
  // 	"graduationDate": "May 2024",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 60000,
  // 	"contacts": "+7(642)816-53-23",
  // 	"about": "Через 20 лет вы будете больше разочарованы теми вещами, которые вы не делали, чем теми, которые вы сделали. Так отчальте от тихой пристани. Почувствуйте попутный ветер в вашем парусе. Двигайтесь вперед, действуйте, открывайте!",
  // 	"workExpirience": [exp3, exp1, exp2]
  // },
  // {
  // 	"firstName": "Zoe",
  // 	"lastName": "Stewart",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Yekaterinburg",
  // 	"age": 49,
  // 	"responses": 28,
  // 	"completedTestTasks": 2,
  // 	"interviews": 6,
  // 	"course": "Java-разработчик",
  // 	"graduationDate": "Dec 2023",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 45000,
  // 	"contacts": "+7(463)422-94-76",
  // 	"about": "Что-то недоброе таится в мужчинах, избегающих вина, игр, общества прелестных женщин, застольной беседы. Такие люди или тяжело больны, или втайне ненавидят окружающих. Правда, возможны исключения.",
  // 	"workExpirience": [exp2, exp1, exp3]
  // },
  // {
  // 	"firstName": "Acton",
  // 	"lastName": "Cash",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Ivangorod",
  // 	"age": 49,
  // 	"responses": 28,
  // 	"completedTestTasks": 8,
  // 	"interviews": 16,
  // 	"course": "Python-разработчик плюс",
  // 	"graduationDate": "Jan 2024",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 40000,
  // 	"contacts": "+7(154)541-77-41",
  // 	"about": "Что-то недоброе таится в мужчинах, избегающих вина, игр, общества прелестных женщин, застольной беседы. Такие люди или тяжело больны, или втайне ненавидят окружающих. Правда, возможны исключения.",
  // 	"workExpirience": [exp2, exp3, exp1]
  // },
  // {
  // 	"firstName": "Alisa",
  // 	"lastName": "Glover",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Saint Petersburg",
  // 	"age": 41,
  // 	"responses": 25,
  // 	"completedTestTasks": 2,
  // 	"interviews": 7,
  // 	"course": "Фронтенд-разработчик",
  // 	"graduationDate": "May 2023",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 55000,
  // 	"contacts": "+7(297)120-47-58",
  // 	"about": "Я помню чудное мгновенье: Передо мной явилась ты, Как мимолетное виденье, Как гений чистой красоты.",
  // 	"workExpirience": [exp1, exp2, exp3]
  // },
  // {
  // 	"firstName": "Russell",
  // 	"lastName": "Henry",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Satka",
  // 	"age": 57,
  // 	"responses": 21,
  // 	"completedTestTasks": 2,
  // 	"interviews": 18,
  // 	"course": "Cтарт в IT",
  // 	"graduationDate": "Jun 2024",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 90000,
  // 	"contacts": "+7(544)964-11-17",
  // 	"about": "Я помню чудное мгновенье: Передо мной явилась ты, Как мимолетное виденье, Как гений чистой красоты.",
  // 	"workExpirience": [exp3, exp1, exp2]
  // },
  // {
  // 	"firstName": "Todd",
  // 	"lastName": "Ferguson",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Kemerovo",
  // 	"age": 32,
  // 	"responses": 26,
  // 	"completedTestTasks": 10,
  // 	"interviews": 32,
  // 	"course": "Системный аналитик",
  // 	"graduationDate": "Sep 2023",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 50000,
  // 	"contacts": "+7(713)257-50-53",
  // 	"about": "Что разум человека может постигнуть и во что он может поверить, того он способен достичь",
  // 	"workExpirience": [exp2, exp1, exp3]
  // },
  // {
  // 	"firstName": "Isabella",
  // 	"lastName": "Ross",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Kaliningrad",
  // 	"age": 30,
  // 	"responses": 27,
  // 	"completedTestTasks": 5,
  // 	"interviews": 2,
  // 	"course": "Специалист по Data Science плюс",
  // 	"graduationDate": "Jun 2023",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 60000,
  // 	"contacts": "+7(966)270-89-18",
  // 	"about": "Что разум человека может постигнуть и во что он может поверить, того он способен достичь",
  // 	"workExpirience": [exp2, exp3, exp1]
  // },
  // {
  // 	"firstName": "Whitney",
  // 	"lastName": "Berg",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Rostov",
  // 	"age": 44,
  // 	"responses": 22,
  // 	"completedTestTasks": 9,
  // 	"interviews": 30,
  // 	"course": "Графический дизайнер",
  // 	"graduationDate": "Aug 2023",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 45000,
  // 	"contacts": "+7(121)544-21-18",
  // 	"about": "Стремитесь не к успеху, а к ценностям, которые он дает",
  // 	"workExpirience": [exp1, exp2, exp3]
  // },
  // {
  // 	"firstName": "Shay",
  // 	"lastName": "O'donnell",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Smolensk",
  // 	"age": 20,
  // 	"responses": 32,
  // 	"completedTestTasks": 2,
  // 	"interviews": 10,
  // 	"course": "iOS-разработчик",
  // 	"graduationDate": "Oct 2023",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 40000,
  // 	"contacts": "+7(618)477-18-18",
  // 	"about": "Стремитесь не к успеху, а к ценностям, которые он дает",
  // 	"workExpirience": [exp3, exp1, exp2]
  // },
  // {
  // 	"firstName": "Tatum",
  // 	"lastName": "Stephenson",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Tambov",
  // 	"age": 22,
  // 	"responses": 27,
  // 	"completedTestTasks": 7,
  // 	"interviews": 16,
  // 	"course": "Android-разработчик",
  // 	"graduationDate": "Oct 2024",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 55000,
  // 	"contacts": "+7(320)123-33-87",
  // 	"about": "Я ничьих мнений не разделяю; я имею свои.",
  // 	"workExpirience": [exp2, exp1, exp3]
  // },
  // {
  // 	"firstName": "Uriah",
  // 	"lastName": "Mclaughlin",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Vladimir",
  // 	"age": 46,
  // 	"responses": 31,
  // 	"completedTestTasks": 7,
  // 	"interviews": 0,
  // 	"course": "Веб-дизайнер",
  // 	"graduationDate": "Feb 2024",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 90000,
  // 	"contacts": "+7(836)855-27-11",
  // 	"about": "Я ничьих мнений не разделяю; я имею свои.",
  // 	"workExpirience": [exp2, exp3, exp1]
  // },
  // {
  // 	"firstName": "Kylynn",
  // 	"lastName": "Norton",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Saratov",
  // 	"age": 46,
  // 	"responses": 16,
  // 	"completedTestTasks": 6,
  // 	"interviews": 22,
  // 	"course": "Веб-дизайнер",
  // 	"graduationDate": "Jun 2024",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 50000,
  // 	"contacts": "+7(239)134-85-51",
  // 	"about": "За свою карьеру я пропустил более 9000 бросков, проиграл почти 300 игр. 26 раз мне доверяли сделать финальный победный бросок, и я промахивался. Я терпел поражения снова, и снова, и снова. И именно поэтому я добился успеха.",
  // 	"workExpirience": [exp1, exp2, exp3]
  // },
  // {
  // 	"firstName": "Randall",
  // 	"lastName": "Hebert",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Saratov",
  // 	"age": 48,
  // 	"responses": 9,
  // 	"completedTestTasks": 6,
  // 	"interviews": 22,
  // 	"course": "Разработчик C++",
  // 	"graduationDate": "Sep 2023",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 60000,
  // 	"contacts": "+7(184)324-74-46",
  // 	"about": "За свою карьеру я пропустил более 9000 бросков, проиграл почти 300 игр. 26 раз мне доверяли сделать финальный победный бросок, и я промахивался. Я терпел поражения снова, и снова, и снова. И именно поэтому я добился успеха.",
  // 	"workExpirience": [exp3, exp1, exp2]
  // },
  // {
  // 	"firstName": "Patricia",
  // 	"lastName": "Cline",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Tolyatti",
  // 	"age": 18,
  // 	"responses": 28,
  // 	"completedTestTasks": 8,
  // 	"interviews": 8,
  // 	"course": "Java-разработчик",
  // 	"graduationDate": "Sep 2023",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 45000,
  // 	"contacts": "+7(597)641-51-82",
  // 	"about": "Через 20 лет вы будете больше разочарованы теми вещами, которые вы не делали, чем теми, которые вы сделали. Так отчальте от тихой пристани. Почувствуйте попутный ветер в вашем парусе. Двигайтесь вперед, действуйте, открывайте!",
  // 	"workExpirience": [exp2, exp1, exp3]
  // },
  // {
  // 	"firstName": "Hayfa",
  // 	"lastName": "Barnes",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Lipetsk",
  // 	"age": 58,
  // 	"responses": 10,
  // 	"completedTestTasks": 5,
  // 	"interviews": 6,
  // 	"course": "Python-разработчик плюс",
  // 	"graduationDate": "Mar 2024",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 40000,
  // 	"contacts": "+7(653)177-85-14",
  // 	"about": "Через 20 лет вы будете больше разочарованы теми вещами, которые вы не делали, чем теми, которые вы сделали. Так отчальте от тихой пристани. Почувствуйте попутный ветер в вашем парусе. Двигайтесь вперед, действуйте, открывайте!",
  // 	"workExpirience": [exp2, exp3, exp1]
  // },
  // {
  // 	"firstName": "Cole",
  // 	"lastName": "Stanley",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Solvychegodsk",
  // 	"age": 41,
  // 	"responses": 18,
  // 	"completedTestTasks": 8,
  // 	"interviews": 12,
  // 	"course": "Фронтенд-разработчик",
  // 	"graduationDate": "Dec 2022",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 55000,
  // 	"contacts": "+7(264)688-88-21",
  // 	"about": "Что-то недоброе таится в мужчинах, избегающих вина, игр, общества прелестных женщин, застольной беседы. Такие люди или тяжело больны, или втайне ненавидят окружающих. Правда, возможны исключения.",
  // 	"workExpirience": [exp1, exp2, exp3]
  // },
  // {
  // 	"firstName": "Kelsey",
  // 	"lastName": "Silva",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Tyumen",
  // 	"age": 25,
  // 	"responses": 26,
  // 	"completedTestTasks": 7,
  // 	"interviews": 21,
  // 	"course": "Cтарт в IT",
  // 	"graduationDate": "Jun 2024",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 90000,
  // 	"contacts": "+7(494)355-82-72",
  // 	"about": "Что-то недоброе таится в мужчинах, избегающих вина, игр, общества прелестных женщин, застольной беседы. Такие люди или тяжело больны, или втайне ненавидят окружающих. Правда, возможны исключения.",
  // 	"workExpirience": [exp3, exp1, exp2]
  // },
  // {
  // 	"firstName": "Imani",
  // 	"lastName": "Haney",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Pskov",
  // 	"age": 20,
  // 	"responses": 5,
  // 	"completedTestTasks": 6,
  // 	"interviews": 30,
  // 	"course": "Системный аналитик",
  // 	"graduationDate": "Jun 2023",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 50000,
  // 	"contacts": "+7(273)858-16-46",
  // 	"about": "Я помню чудное мгновенье: Передо мной явилась ты, Как мимолетное виденье, Как гений чистой красоты.",
  // 	"workExpirience": [exp2, exp1, exp3]
  // },
  // {
  // 	"firstName": "Cole",
  // 	"lastName": "Knapp",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Nizhny",
  // 	"age": 22,
  // 	"responses": 9,
  // 	"completedTestTasks": 8,
  // 	"interviews": 15,
  // 	"course": "Специалист по Data Science плюс",
  // 	"graduationDate": "Nov 2023",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 60000,
  // 	"contacts": "+7(320)534-73-44",
  // 	"about": "Я помню чудное мгновенье: Передо мной явилась ты, Как мимолетное виденье, Как гений чистой красоты.",
  // 	"workExpirience": [exp2, exp3, exp1]
  // },
  // {
  // 	"firstName": "Patrick",
  // 	"lastName": "Walsh",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Voronezh",
  // 	"age": 26,
  // 	"responses": 16,
  // 	"completedTestTasks": 6,
  // 	"interviews": 14,
  // 	"course": "Графический дизайнер",
  // 	"graduationDate": "Dec 2023",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 45000,
  // 	"contacts": "+7(150)821-47-58",
  // 	"about": "Что разум человека может постигнуть и во что он может поверить, того он способен достичь",
  // 	"workExpirience": [exp1, exp2, exp3]
  // },
  // {
  // 	"firstName": "Yolanda",
  // 	"lastName": "Garcia",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Ulyanovsk",
  // 	"age": 45,
  // 	"responses": 10,
  // 	"completedTestTasks": 6,
  // 	"interviews": 13,
  // 	"course": "iOS-разработчик",
  // 	"graduationDate": "May 2023",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 40000,
  // 	"contacts": "+7(207)266-24-00",
  // 	"about": "Что разум человека может постигнуть и во что он может поверить, того он способен достичь",
  // 	"workExpirience": [exp3, exp1, exp2]
  // },
  // {
  // 	"firstName": "Otto",
  // 	"lastName": "Wilkins",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Volgograd",
  // 	"age": 45,
  // 	"responses": 18,
  // 	"completedTestTasks": 7,
  // 	"interviews": 14,
  // 	"course": "Android-разработчик",
  // 	"graduationDate": "Nov 2023",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 55000,
  // 	"contacts": "+7(816)216-47-11",
  // 	"about": "Стремитесь не к успеху, а к ценностям, которые он дает",
  // 	"workExpirience": [exp2, exp1, exp3]
  // },
  // {
  // 	"firstName": "Ramona",
  // 	"lastName": "Dickson",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Novosibirsk",
  // 	"age": 19,
  // 	"responses": 30,
  // 	"completedTestTasks": 7,
  // 	"interviews": 9,
  // 	"course": "Веб-дизайнер",
  // 	"graduationDate": "Jan 2024",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 90000,
  // 	"contacts": "+7(956)753-24-41",
  // 	"about": "Стремитесь не к успеху, а к ценностям, которые он дает",
  // 	"workExpirience": [exp2, exp3, exp1]
  // },
  // {
  // 	"firstName": "Bernard",
  // 	"lastName": "Holloway",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Tula",
  // 	"age": 32,
  // 	"responses": 5,
  // 	"completedTestTasks": 1,
  // 	"interviews": 20,
  // 	"course": "Веб-дизайнер",
  // 	"graduationDate": "Feb 2023",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 50000,
  // 	"contacts": "+7(548)365-55-18",
  // 	"about": "Я ничьих мнений не разделяю; я имею свои.",
  // 	"workExpirience": [exp1, exp2, exp3]
  // },
  // {
  // 	"firstName": "Harriet",
  // 	"lastName": "Hess",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Kasli",
  // 	"age": 34,
  // 	"responses": 23,
  // 	"completedTestTasks": 2,
  // 	"interviews": 20,
  // 	"course": "Разработчик C++",
  // 	"graduationDate": "Jul 2023",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 60000,
  // 	"contacts": "+7(267)853-82-77",
  // 	"about": "Я ничьих мнений не разделяю; я имею свои.",
  // 	"workExpirience": [exp3, exp1, exp2]
  // },
  // {
  // 	"firstName": "Lacey",
  // 	"lastName": "Herring",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Tomsk",
  // 	"age": 47,
  // 	"responses": 2,
  // 	"completedTestTasks": 7,
  // 	"interviews": 11,
  // 	"course": "Java-разработчик",
  // 	"graduationDate": "Dec 2022",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 45000,
  // 	"contacts": "+7(707)815-01-37",
  // 	"about": "За свою карьеру я пропустил более 9000 бросков, проиграл почти 300 игр. 26 раз мне доверяли сделать финальный победный бросок, и я промахивался. Я терпел поражения снова, и снова, и снова. И именно поэтому я добился успеха.",
  // 	"workExpirience": [exp2, exp1, exp3]
  // },
  // {
  // 	"firstName": "Madaline",
  // 	"lastName": "Curtis",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Volgograd",
  // 	"age": 53,
  // 	"responses": 23,
  // 	"completedTestTasks": 9,
  // 	"interviews": 8,
  // 	"course": "Python-разработчик плюс",
  // 	"graduationDate": "Apr 2023",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 40000,
  // 	"contacts": "+7(922)314-85-93",
  // 	"about": "За свою карьеру я пропустил более 9000 бросков, проиграл почти 300 игр. 26 раз мне доверяли сделать финальный победный бросок, и я промахивался. Я терпел поражения снова, и снова, и снова. И именно поэтому я добился успеха.",
  // 	"workExpirience": [exp2, exp3, exp1]
  // },
  // {
  // 	"firstName": "Lunea",
  // 	"lastName": "Hardin",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Yaroslavl",
  // 	"age": 38,
  // 	"responses": 33,
  // 	"completedTestTasks": 4,
  // 	"interviews": 27,
  // 	"course": "Фронтенд-разработчик",
  // 	"graduationDate": "Jul 2023",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 55000,
  // 	"contacts": "+7(977)655-87-33",
  // 	"about": "Через 20 лет вы будете больше разочарованы теми вещами, которые вы не делали, чем теми, которые вы сделали. Так отчальте от тихой пристани. Почувствуйте попутный ветер в вашем парусе. Двигайтесь вперед, действуйте, открывайте!",
  // 	"workExpirience": [exp1, exp2, exp3]
  // },
  // {
  // 	"firstName": "Anne",
  // 	"lastName": "Donovan",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Kostroma",
  // 	"age": 40,
  // 	"responses": 1,
  // 	"completedTestTasks": 3,
  // 	"interviews": 5,
  // 	"course": "Cтарт в IT",
  // 	"graduationDate": "Mar 2023",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 90000,
  // 	"contacts": "+7(670)947-07-19",
  // 	"about": "Через 20 лет вы будете больше разочарованы теми вещами, которые вы не делали, чем теми, которые вы сделали. Так отчальте от тихой пристани. Почувствуйте попутный ветер в вашем парусе. Двигайтесь вперед, действуйте, открывайте!",
  // 	"workExpirience": [exp3, exp1, exp2]
  // },
  // {
  // 	"firstName": "Abbot",
  // 	"lastName": "Graves",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Akhtubinsk",
  // 	"age": 38,
  // 	"responses": 11,
  // 	"completedTestTasks": 2,
  // 	"interviews": 18,
  // 	"course": "Системный аналитик",
  // 	"graduationDate": "Jul 2024",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 50000,
  // 	"contacts": "+7(558)328-88-35",
  // 	"about": "Что-то недоброе таится в мужчинах, избегающих вина, игр, общества прелестных женщин, застольной беседы. Такие люди или тяжело больны, или втайне ненавидят окружающих. Правда, возможны исключения.",
  // 	"workExpirience": [exp2, exp1, exp3]
  // },
  // {
  // 	"firstName": "Lani",
  // 	"lastName": "Cotton",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Murmansk",
  // 	"age": 19,
  // 	"responses": 20,
  // 	"completedTestTasks": 6,
  // 	"interviews": 16,
  // 	"course": "Специалист по Data Science плюс",
  // 	"graduationDate": "Nov 2022",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 60000,
  // 	"contacts": "+7(333)874-44-27",
  // 	"about": "Что-то недоброе таится в мужчинах, избегающих вина, игр, общества прелестных женщин, застольной беседы. Такие люди или тяжело больны, или втайне ненавидят окружающих. Правда, возможны исключения.",
  // 	"workExpirience": [exp2, exp3, exp1]
  // },
  // {
  // 	"firstName": "Cherokee",
  // 	"lastName": "Lowe",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Vladimir",
  // 	"age": 52,
  // 	"responses": 15,
  // 	"completedTestTasks": 2,
  // 	"interviews": 32,
  // 	"course": "Графический дизайнер",
  // 	"graduationDate": "Apr 2023",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 45000,
  // 	"contacts": "+7(313)652-97-27",
  // 	"about": "Я помню чудное мгновенье: Передо мной явилась ты, Как мимолетное виденье, Как гений чистой красоты.",
  // 	"workExpirience": [exp1, exp2, exp3]
  // },
  // {
  // 	"firstName": "Dorian",
  // 	"lastName": "Conley",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Omsk",
  // 	"age": 23,
  // 	"responses": 12,
  // 	"completedTestTasks": 4,
  // 	"interviews": 18,
  // 	"course": "iOS-разработчик",
  // 	"graduationDate": "Jun 2024",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 40000,
  // 	"contacts": "+7(384)531-02-12",
  // 	"about": "Я помню чудное мгновенье: Передо мной явилась ты, Как мимолетное виденье, Как гений чистой красоты.",
  // 	"workExpirience": [exp3, exp1, exp2]
  // },
  // {
  // 	"firstName": "Noble",
  // 	"lastName": "Velez",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Mirny",
  // 	"age": 19,
  // 	"responses": 31,
  // 	"completedTestTasks": 4,
  // 	"interviews": 3,
  // 	"course": "Android-разработчик",
  // 	"graduationDate": "Jan 2023",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 55000,
  // 	"contacts": "+7(157)704-66-74",
  // 	"about": "Что разум человека может постигнуть и во что он может поверить, того он способен достичь",
  // 	"workExpirience": [exp2, exp1, exp3]
  // },
  // {
  // 	"firstName": "Omar",
  // 	"lastName": "Cannon",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Yaroslavl",
  // 	"age": 24,
  // 	"responses": 18,
  // 	"completedTestTasks": 9,
  // 	"interviews": 5,
  // 	"course": "Веб-дизайнер",
  // 	"graduationDate": "Jul 2024",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 90000,
  // 	"contacts": "+7(135)018-56-26",
  // 	"about": "Что разум человека может постигнуть и во что он может поверить, того он способен достичь",
  // 	"workExpirience": [exp2, exp3, exp1]
  // },
  // {
  // 	"firstName": "Xenos",
  // 	"lastName": "Gamble",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Ryazan",
  // 	"age": 50,
  // 	"responses": 23,
  // 	"completedTestTasks": 8,
  // 	"interviews": 25,
  // 	"course": "Веб-дизайнер",
  // 	"graduationDate": "Dec 2023",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 50000,
  // 	"contacts": "+7(922)488-02-32",
  // 	"about": "Стремитесь не к успеху, а к ценностям, которые он дает",
  // 	"workExpirience": [exp1, exp2, exp3]
  // },
  // {
  // 	"firstName": "Quin",
  // 	"lastName": "Snider",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Rostov",
  // 	"age": 18,
  // 	"responses": 32,
  // 	"completedTestTasks": 3,
  // 	"interviews": 27,
  // 	"course": "Разработчик C++",
  // 	"graduationDate": "Jul 2023",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 60000,
  // 	"contacts": "+7(434)177-58-41",
  // 	"about": "Стремитесь не к успеху, а к ценностям, которые он дает",
  // 	"workExpirience": [exp3, exp1, exp2]
  // },
  // {
  // 	"firstName": "Leandra",
  // 	"lastName": "Hudson",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Rostov",
  // 	"age": 20,
  // 	"responses": 5,
  // 	"completedTestTasks": 10,
  // 	"interviews": 9,
  // 	"course": "Java-разработчик",
  // 	"graduationDate": "Dec 2023",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 45000,
  // 	"contacts": "+7(883)770-32-20",
  // 	"about": "Я ничьих мнений не разделяю; я имею свои.",
  // 	"workExpirience": [exp2, exp1, exp3]
  // },
  // {
  // 	"firstName": "Kennedy",
  // 	"lastName": "Kent",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Samara",
  // 	"age": 58,
  // 	"responses": 8,
  // 	"completedTestTasks": 4,
  // 	"interviews": 24,
  // 	"course": "Python-разработчик плюс",
  // 	"graduationDate": "May 2023",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 40000,
  // 	"contacts": "+7(780)947-38-80",
  // 	"about": "Я ничьих мнений не разделяю; я имею свои.",
  // 	"workExpirience": [exp2, exp3, exp1]
  // },
  // {
  // 	"firstName": "Sheila",
  // 	"lastName": "Booth",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Penza",
  // 	"age": 56,
  // 	"responses": 29,
  // 	"completedTestTasks": 9,
  // 	"interviews": 4,
  // 	"course": "Фронтенд-разработчик",
  // 	"graduationDate": "Sep 2023",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 55000,
  // 	"contacts": "+7(041)452-42-39",
  // 	"about": "За свою карьеру я пропустил более 9000 бросков, проиграл почти 300 игр. 26 раз мне доверяли сделать финальный победный бросок, и я промахивался. Я терпел поражения снова, и снова, и снова. И именно поэтому я добился успеха.",
  // 	"workExpirience": [exp1, exp2, exp3]
  // },
  // {
  // 	"firstName": "Damon",
  // 	"lastName": "Cannon",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Volgograd",
  // 	"age": 22,
  // 	"responses": 0,
  // 	"completedTestTasks": 9,
  // 	"interviews": 28,
  // 	"course": "Cтарт в IT",
  // 	"graduationDate": "Oct 2024",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 90000,
  // 	"contacts": "+7(327)270-18-55",
  // 	"about": "За свою карьеру я пропустил более 9000 бросков, проиграл почти 300 игр. 26 раз мне доверяли сделать финальный победный бросок, и я промахивался. Я терпел поражения снова, и снова, и снова. И именно поэтому я добился успеха.",
  // 	"workExpirience": [exp3, exp1, exp2]
  // },
  // {
  // 	"firstName": "Grant",
  // 	"lastName": "Avila",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Grayvoron",
  // 	"age": 56,
  // 	"responses": 4,
  // 	"completedTestTasks": 8,
  // 	"interviews": 9,
  // 	"course": "Системный аналитик",
  // 	"graduationDate": "Jun 2024",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 50000,
  // 	"contacts": "+7(386)313-32-22",
  // 	"about": "Через 20 лет вы будете больше разочарованы теми вещами, которые вы не делали, чем теми, которые вы сделали. Так отчальте от тихой пристани. Почувствуйте попутный ветер в вашем парусе. Двигайтесь вперед, действуйте, открывайте!",
  // 	"workExpirience": [exp2, exp1, exp3]
  // },
  // {
  // 	"firstName": "Yardley",
  // 	"lastName": "Haley",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Cherepovets",
  // 	"age": 46,
  // 	"responses": 26,
  // 	"completedTestTasks": 8,
  // 	"interviews": 18,
  // 	"course": "Специалист по Data Science плюс",
  // 	"graduationDate": "Dec 2023",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 60000,
  // 	"contacts": "+7(405)425-20-55",
  // 	"about": "Через 20 лет вы будете больше разочарованы теми вещами, которые вы не делали, чем теми, которые вы сделали. Так отчальте от тихой пристани. Почувствуйте попутный ветер в вашем парусе. Двигайтесь вперед, действуйте, открывайте!",
  // 	"workExpirience": [exp2, exp3, exp1]
  // },
  // {
  // 	"firstName": "Aiko",
  // 	"lastName": "England",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Kaliningrad",
  // 	"age": 25,
  // 	"responses": 26,
  // 	"completedTestTasks": 9,
  // 	"interviews": 21,
  // 	"course": "Графический дизайнер",
  // 	"graduationDate": "Feb 2023",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 45000,
  // 	"contacts": "+7(279)475-52-54",
  // 	"about": "Что-то недоброе таится в мужчинах, избегающих вина, игр, общества прелестных женщин, застольной беседы. Такие люди или тяжело больны, или втайне ненавидят окружающих. Правда, возможны исключения.",
  // 	"workExpirience": [exp1, exp2, exp3]
  // },
  // {
  // 	"firstName": "Hayley",
  // 	"lastName": "Sargent",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Voronezh",
  // 	"age": 25,
  // 	"responses": 4,
  // 	"completedTestTasks": 8,
  // 	"interviews": 2,
  // 	"course": "iOS-разработчик",
  // 	"graduationDate": "Oct 2023",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 40000,
  // 	"contacts": "+7(674)554-46-35",
  // 	"about": "Что-то недоброе таится в мужчинах, избегающих вина, игр, общества прелестных женщин, застольной беседы. Такие люди или тяжело больны, или втайне ненавидят окружающих. Правда, возможны исключения.",
  // 	"workExpirience": [exp3, exp1, exp2]
  // },
  // {
  // 	"firstName": "Lucas",
  // 	"lastName": "Fleming",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Troitsk",
  // 	"age": 23,
  // 	"responses": 20,
  // 	"completedTestTasks": 8,
  // 	"interviews": 6,
  // 	"course": "Android-разработчик",
  // 	"graduationDate": "Dec 2023",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 55000,
  // 	"contacts": "+7(533)866-44-36",
  // 	"about": "Я помню чудное мгновенье: Передо мной явилась ты, Как мимолетное виденье, Как гений чистой красоты.",
  // 	"workExpirience": [exp2, exp1, exp3]
  // },
  // {
  // 	"firstName": "Alan",
  // 	"lastName": "Velez",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Smolensk",
  // 	"age": 51,
  // 	"responses": 19,
  // 	"completedTestTasks": 6,
  // 	"interviews": 11,
  // 	"course": "Веб-дизайнер",
  // 	"graduationDate": "May 2023",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 90000,
  // 	"contacts": "+7(880)741-31-74",
  // 	"about": "Я помню чудное мгновенье: Передо мной явилась ты, Как мимолетное виденье, Как гений чистой красоты.",
  // 	"workExpirience": [exp2, exp3, exp1]
  // },
  // {
  // 	"firstName": "Austin",
  // 	"lastName": "Dorsey",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Shebekino",
  // 	"age": 51,
  // 	"responses": 27,
  // 	"completedTestTasks": 4,
  // 	"interviews": 32,
  // 	"course": "Веб-дизайнер",
  // 	"graduationDate": "Feb 2024",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 50000,
  // 	"contacts": "+7(760)119-84-67",
  // 	"about": "Что разум человека может постигнуть и во что он может поверить, того он способен достичь",
  // 	"workExpirience": [exp1, exp2, exp3]
  // },
  // {
  // 	"firstName": "Lee",
  // 	"lastName": "Gibbs",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Belgorod",
  // 	"age": 30,
  // 	"responses": 7,
  // 	"completedTestTasks": 4,
  // 	"interviews": 8,
  // 	"course": "Разработчик C++",
  // 	"graduationDate": "Sep 2023",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 60000,
  // 	"contacts": "+7(061)411-80-99",
  // 	"about": "Что разум человека может постигнуть и во что он может поверить, того он способен достичь",
  // 	"workExpirience": [exp3, exp1, exp2]
  // },
  // {
  // 	"firstName": "Shoshana",
  // 	"lastName": "Preston",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Saratov",
  // 	"age": 54,
  // 	"responses": 5,
  // 	"completedTestTasks": 1,
  // 	"interviews": 32,
  // 	"course": "Java-разработчик",
  // 	"graduationDate": "Feb 2024",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 45000,
  // 	"contacts": "+7(533)374-94-17",
  // 	"about": "Стремитесь не к успеху, а к ценностям, которые он дает",
  // 	"workExpirience": [exp2, exp1, exp3]
  // },
  // {
  // 	"firstName": "Tobias",
  // 	"lastName": "Chase",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Saint Petersburg",
  // 	"age": 49,
  // 	"responses": 26,
  // 	"completedTestTasks": 7,
  // 	"interviews": 26,
  // 	"course": "Python-разработчик плюс",
  // 	"graduationDate": "Apr 2024",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 40000,
  // 	"contacts": "+7(870)546-15-67",
  // 	"about": "Стремитесь не к успеху, а к ценностям, которые он дает",
  // 	"workExpirience": [exp2, exp3, exp1]
  // },
  // {
  // 	"firstName": "Channing",
  // 	"lastName": "Hickman",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Oryol",
  // 	"age": 39,
  // 	"responses": 25,
  // 	"completedTestTasks": 10,
  // 	"interviews": 29,
  // 	"course": "Фронтенд-разработчик",
  // 	"graduationDate": "Jan 2023",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 55000,
  // 	"contacts": "+7(309)430-58-33",
  // 	"about": "Я ничьих мнений не разделяю; я имею свои.",
  // 	"workExpirience": [exp1, exp2, exp3]
  // },
  // {
  // 	"firstName": "Felicia",
  // 	"lastName": "Mckee",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Voronezh",
  // 	"age": 46,
  // 	"responses": 11,
  // 	"completedTestTasks": 9,
  // 	"interviews": 6,
  // 	"course": "Cтарт в IT",
  // 	"graduationDate": "May 2023",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 90000,
  // 	"contacts": "+7(538)687-04-77",
  // 	"about": "Я ничьих мнений не разделяю; я имею свои.",
  // 	"workExpirience": [exp3, exp1, exp2]
  // },
  // {
  // 	"firstName": "Matthew",
  // 	"lastName": "Sanders",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Kaluga",
  // 	"age": 22,
  // 	"responses": 5,
  // 	"completedTestTasks": 2,
  // 	"interviews": 12,
  // 	"course": "Системный аналитик",
  // 	"graduationDate": "Sep 2023",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 50000,
  // 	"contacts": "+7(672)539-93-54",
  // 	"about": "За свою карьеру я пропустил более 9000 бросков, проиграл почти 300 игр. 26 раз мне доверяли сделать финальный победный бросок, и я промахивался. Я терпел поражения снова, и снова, и снова. И именно поэтому я добился успеха.",
  // 	"workExpirience": [exp2, exp1, exp3]
  // },
  // {
  // 	"firstName": "Jade",
  // 	"lastName": "Robles",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Akhtubinsk",
  // 	"age": 36,
  // 	"responses": 26,
  // 	"completedTestTasks": 7,
  // 	"interviews": 8,
  // 	"course": "Специалист по Data Science плюс",
  // 	"graduationDate": "Feb 2024",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 60000,
  // 	"contacts": "+7(664)251-34-48",
  // 	"about": "За свою карьеру я пропустил более 9000 бросков, проиграл почти 300 игр. 26 раз мне доверяли сделать финальный победный бросок, и я промахивался. Я терпел поражения снова, и снова, и снова. И именно поэтому я добился успеха.",
  // 	"workExpirience": [exp2, exp3, exp1]
  // },
  // {
  // 	"firstName": "Amos",
  // 	"lastName": "Jones",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Kaliningrad",
  // 	"age": 22,
  // 	"responses": 33,
  // 	"completedTestTasks": 1,
  // 	"interviews": 10,
  // 	"course": "Графический дизайнер",
  // 	"graduationDate": "Jun 2024",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 45000,
  // 	"contacts": "+7(652)768-72-62",
  // 	"about": "Через 20 лет вы будете больше разочарованы теми вещами, которые вы не делали, чем теми, которые вы сделали. Так отчальте от тихой пристани. Почувствуйте попутный ветер в вашем парусе. Двигайтесь вперед, действуйте, открывайте!",
  // 	"workExpirience": [exp1, exp2, exp3]
  // },
  // {
  // 	"firstName": "Katell",
  // 	"lastName": "Schneider",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Sevastopol",
  // 	"age": 30,
  // 	"responses": 18,
  // 	"completedTestTasks": 3,
  // 	"interviews": 22,
  // 	"course": "iOS-разработчик",
  // 	"graduationDate": "Feb 2024",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 40000,
  // 	"contacts": "+7(607)375-19-88",
  // 	"about": "Через 20 лет вы будете больше разочарованы теми вещами, которые вы не делали, чем теми, которые вы сделали. Так отчальте от тихой пристани. Почувствуйте попутный ветер в вашем парусе. Двигайтесь вперед, действуйте, открывайте!",
  // 	"workExpirience": [exp3, exp1, exp2]
  // },
  // {
  // 	"firstName": "Leila",
  // 	"lastName": "Gardner",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Irkutsk",
  // 	"age": 24,
  // 	"responses": 17,
  // 	"completedTestTasks": 2,
  // 	"interviews": 10,
  // 	"course": "Android-разработчик",
  // 	"graduationDate": "Dec 2023",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 55000,
  // 	"contacts": "+7(765)276-37-48",
  // 	"about": "Что-то недоброе таится в мужчинах, избегающих вина, игр, общества прелестных женщин, застольной беседы. Такие люди или тяжело больны, или втайне ненавидят окружающих. Правда, возможны исключения.",
  // 	"workExpirience": [exp2, exp1, exp3]
  // },
  // {
  // 	"firstName": "Lewis",
  // 	"lastName": "Garrett",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Zlatoust",
  // 	"age": 30,
  // 	"responses": 6,
  // 	"completedTestTasks": 9,
  // 	"interviews": 5,
  // 	"course": "Веб-дизайнер",
  // 	"graduationDate": "Nov 2023",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 90000,
  // 	"contacts": "+7(960)158-36-68",
  // 	"about": "Что-то недоброе таится в мужчинах, избегающих вина, игр, общества прелестных женщин, застольной беседы. Такие люди или тяжело больны, или втайне ненавидят окружающих. Правда, возможны исключения.",
  // 	"workExpirience": [exp2, exp3, exp1]
  // },
  // {
  // 	"firstName": "Aidan",
  // 	"lastName": "Sanders",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Grayvoron",
  // 	"age": 42,
  // 	"responses": 25,
  // 	"completedTestTasks": 5,
  // 	"interviews": 25,
  // 	"course": "Веб-дизайнер",
  // 	"graduationDate": "May 2023",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 50000,
  // 	"contacts": "+7(481)243-94-89",
  // 	"about": "Я помню чудное мгновенье: Передо мной явилась ты, Как мимолетное виденье, Как гений чистой красоты.",
  // 	"workExpirience": [exp1, exp2, exp3]
  // },
  // {
  // 	"firstName": "Veronica",
  // 	"lastName": "Rivers",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": true,
  // 	"city": "Koryazhma",
  // 	"age": 24,
  // 	"responses": 23,
  // 	"completedTestTasks": 3,
  // 	"interviews": 1,
  // 	"course": "Разработчик C++",
  // 	"graduationDate": "Apr 2024",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 60000,
  // 	"contacts": "+7(527)032-42-53",
  // 	"about": "Я помню чудное мгновенье: Передо мной явилась ты, Как мимолетное виденье, Как гений чистой красоты.",
  // 	"workExpirience": [exp3, exp1, exp2]
  // },
  // {
  // 	"firstName": "Hilary",
  // 	"lastName": "Chen",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Sakhalin",
  // 	"age": 55,
  // 	"responses": 2,
  // 	"completedTestTasks": 3,
  // 	"interviews": 32,
  // 	"course": "Java-разработчик",
  // 	"graduationDate": "Sep 2024",
  // 	"workFormat": "офис",
  // 	"grade": "Junior",
  // 	"salary": 45000,
  // 	"contacts": "+7(311)658-46-87",
  // 	"about": "Что разум человека может постигнуть и во что он может поверить, того он способен достичь",
  // 	"workExpirience": [exp2, exp1, exp3]
  // },
  // {
  // 	"firstName": "Garth",
  // 	"lastName": "Rowland",
  // 	"avatar": "https://random.imagecdn.app/200/200",
  // 	"isWinner": false,
  // 	"city": "Kostroma",
  // 	"age": 53,
  // 	"responses": 3,
  // 	"completedTestTasks": 5,
  // 	"interviews": 2,
  // 	"course": "Python-разработчик плюс",
  // 	"graduationDate": "Aug 2024",
  // 	"workFormat": "удаленный",
  // 	"grade": "middle",
  // 	"salary": 40000,
  // 	"contacts": "+7(906)641-51-85",
  // 	"about": "Что разум человека может постигнуть и во что он может поверить, того он способен достичь",
  // 	"workExpirience": [exp2, exp3, exp1]
  // }
];
