export type workExp = {
  workStart: Date; // начало работы
  workEnd: Date; // конец работы
  companyName: string; // название компании
  position: string; // должность
  resp: string; // обязанности
};

export type applicant = {
  firstName: string; // имя
  lastName: string; // фамилия
  avatar: string; // ссылка на аватар в формате url
  isWinner: boolean; // победитель хакатона?
  city: string; // город
  age: number; // возраст
  responses: number; // длина массива откликов
  completedTestTasks: number; // длина массива тестовых
  interviews: number; // длина массива собеседований
  course: string; // название оконченного курса
  graduationDate: Date; // дата окончания (строка формата 'апрель 2023')
  workFormat: string; // формат работы
  // добавила новые поля
  grade: string; // грейд
  salary: number; // зп
  contacts: string; // контакты
  about: string; // о себе
  workExpirience: Array<workExp>; // массив из объектов мест работы
  // добавила еще поля
  studyingStatus: string; // учебный статус
  responseStatus: string; // статус отклика
  workStatus: string; // опыт работы
};

export type applicantsList = Array<applicant>;
const date: Date = new Date();

export const applicantsOld = [
  {
    id: 1,
    firstName: "Анна",
    lastName: "Короткова",
    avatar:
      "https://images.unsplash.com/photo-1693438672953-409b661134fd?auto=format&fit=crop&q=80&w=1887&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    isWinner: false,
    city: "Санкт-Петербург",
    age: 24,
    responses: 40,
    completedTestTasks: 14,
    interviews: 10,
    course: "Дизайнер интерфейсов",
    graduationDate: "апрель 2023",
    workFormat: "удаленный",
    grade: "Junior",
    salary: 50000,
    contacts: "+799999999999",
    status: 3,
    about: "Улыбаюсь и пью кофе",
  },
  {
    id: 2,
    firstName: "Алия",
    lastName: "Шархимуллина",
    avatar:
      "https://images.unsplash.com/photo-1697472106815-829bad01f7b8?auto=format&fit=crop&q=80&w=1887&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    isWinner: false,
    city: "Казань",
    age: 28,
    responses: 1,
    completedTestTasks: 10,
    interviews: 9,
    course: "Web-разработчик",
    graduationDate: "июнь 2022",
    workFormat: "офис",
    grade: "Junior",
    salary: 50000,
    contacts: "+799999999999",
    status: 3,
    about: "Не улыбаюсь и пью винишко",
  },
  {
    id: 3,
    firstName: "Иван",
    lastName: "Иванов",
    avatar:
      "https://images.unsplash.com/photo-1696887350319-86341eda4b71?auto=format&fit=crop&q=80&w=1925&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    isWinner: true,
    city: "Москва",
    age: 35,
    responses: 0,
    completedTestTasks: 0,
    interviews: 0,
    course: "Python-разработчик",
    graduationDate: "август 2023",
    workFormat: "удаленный",
    grade: "Junior",
    salary: 50000,
    contacts: "+799999999999",
    status: 3,
    about: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.`,
  },
  {
    id: 5,
    firstName: "Петр",
    lastName: "Петров",
    avatar:
      "https://images.unsplash.com/photo-1697472925037-e38438b132b0?auto=format&fit=crop&q=80&w=1965&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    isWinner: false,
    city: "Барнаул",
    age: 30,
    responses: 35,
    completedTestTasks: 20,
    interviews: 5,
    course: "Дизайнер интерфейсов",
    graduationDate: "февраль 2023",
    workFormat: "удаленный",
    grade: "Junior",
    salary: 50000,
    contacts: "+799999999999",
    status: 3,
    about: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.`,
  },
  {
    id: 6,
    firstName: "Александра",
    lastName: "Александрова",
    avatar:
      "https://images.unsplash.com/photo-1689193504709-2ccf8bf64be1?auto=format&fit=crop&q=80&w=1887&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    isWinner: true,
    city: "Санкт-Петербург",
    age: 24,
    responses: 0,
    completedTestTasks: 1,
    interviews: 0,
    course: "Дизайнер интерфейсов",
    graduationDate: "апрель 2023",
    workFormat: "удаленный",
    grade: "Junior",
    salary: 50000,
    contacts: "+799999999999",
    about: "Улыбаюсь и пью кофе",
    status: 3,
  },
  {
    id: 7,
    firstName: "Анна",
    lastName: "Короткова",
    avatar:
      "https://images.unsplash.com/photo-1693438672953-409b661134fd?auto=format&fit=crop&q=80&w=1887&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    isWinner: false,
    city: "Санкт-Петербург",
    age: 24,
    responses: 40,
    completedTestTasks: 14,
    interviews: 50,
    course: "Дизайнер интерфейсов",
    graduationDate: "апрель 2023",
    workFormat: "удаленный",
    grade: "Junior",
    salary: 50000,
    contacts: "+799999999999",
    about: "Улыбаюсь и пью кофе",
    status: 4,
  },
  {
    id: 8,
    firstName: "Алия",
    lastName: "Шархимуллина",
    avatar:
      "https://images.unsplash.com/photo-1697472106815-829bad01f7b8?auto=format&fit=crop&q=80&w=1887&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    isWinner: true,
    city: "Казань",
    age: 28,
    responses: 10,
    completedTestTasks: 5,
    interviews: 100,
    course: "Web-разработчик",
    graduationDate: "июнь 2022",
    workFormat: "офис",
    grade: "Junior",
    salary: 50000,
    contacts: "+799999999999",
    about: "Не улыбаюсь и пью винишко",
    status: 6,
  },
  {
    id: 9,
    firstName: "Анна",
    lastName: "Короткова",
    avatar:
      "https://images.unsplash.com/photo-1693438672953-409b661134fd?auto=format&fit=crop&q=80&w=1887&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    isWinner: false,
    city: "Санкт-Петербург",
    age: 24,
    responses: 40,
    completedTestTasks: 14,
    interviews: 10,
    course: "Дизайнер интерфейсов",
    graduationDate: "апрель 2023",
    workFormat: "удаленный",
    grade: "Junior",
    salary: 50000,
    contacts: "+799999999999",
    about: "Улыбаюсь и пью кофе",
    status: 5,
  },
  {
    id: 10,
    firstName: "Алия",
    lastName: "Шархимуллина",
    avatar:
      "https://images.unsplash.com/photo-1697472106815-829bad01f7b8?auto=format&fit=crop&q=80&w=1887&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    isWinner: false,
    city: "Казань",
    age: 28,
    responses: 1,
    completedTestTasks: 10,
    interviews: 9,
    course: "Web-разработчик",
    graduationDate: "июнь 2022",
    workFormat: "офис",
    grade: "Junior",
    salary: 50000,
    contacts: "+799999999999",
    about: "Не улыбаюсь и пью винишко",
    status: 4,
  },
  {
    id: 11,
    firstName: "Иван",
    lastName: "Иванов",
    avatar:
      "https://images.unsplash.com/photo-1696887350319-86341eda4b71?auto=format&fit=crop&q=80&w=1925&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    isWinner: true,
    city: "Москва",
    age: 35,
    responses: 0,
    completedTestTasks: 0,
    interviews: 0,
    course: "Python-разработчик",
    graduationDate: "август 2023",
    workFormat: "удаленный",
    grade: "Junior",
    salary: 50000,
    contacts: "+799999999999",
    status: 2,
    about: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.`,
  },
  {
    id: 12,
    firstName: "Петр",
    lastName: "Петров",
    avatar:
      "https://images.unsplash.com/photo-1697472925037-e38438b132b0?auto=format&fit=crop&q=80&w=1965&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    isWinner: false,
    city: "Барнаул",
    age: 30,
    responses: 35,
    completedTestTasks: 20,
    interviews: 5,
    course: "Дизайнер интерфейсов",
    graduationDate: "февраль 2023",
    workFormat: "удаленный",
    grade: "Junior",
    salary: 50000,
    contacts: "+799999999999",
    status: 1,
    about: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.`,
  },
  {
    id: 13,
    firstName: "Александра",
    lastName: "Александрова",
    avatar:
      "https://images.unsplash.com/photo-1689193504709-2ccf8bf64be1?auto=format&fit=crop&q=80&w=1887&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    isWinner: true,
    city: "Санкт-Петербург",
    age: 24,
    responses: 0,
    completedTestTasks: 1,
    interviews: 0,
    course: "Дизайнер интерфейсов",
    graduationDate: "апрель 2023",
    workFormat: "удаленный",
    grade: "Junior",
    salary: 50000,
    contacts: "+799999999999",
    about: "Улыбаюсь и пью кофе",
    status: 4,
  },
  {
    id: 14,
    firstName: "Анна",
    lastName: "Короткова",
    avatar:
      "https://images.unsplash.com/photo-1693438672953-409b661134fd?auto=format&fit=crop&q=80&w=1887&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    isWinner: false,
    city: "Санкт-Петербург",
    age: 24,
    responses: 40,
    completedTestTasks: 14,
    interviews: 50,
    course: "Дизайнер интерфейсов",
    graduationDate: "апрель 2023",
    workFormat: "удаленный",
    grade: "Junior",
    salary: 50000,
    contacts: "+799999999999",
    about: "Улыбаюсь и пью кофе",
    status: 3,
  },
  {
    id: 15,
    firstName: "Алия",
    lastName: "Шархимуллина",
    avatar:
      "https://images.unsplash.com/photo-1697472106815-829bad01f7b8?auto=format&fit=crop&q=80&w=1887&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    isWinner: true,
    city: "Казань",
    age: 28,
    responses: 10,
    completedTestTasks: 5,
    interviews: 100,
    course: "Web-разработчик",
    graduationDate: "июнь 2022",
    workFormat: "офис",
    grade: "Junior",
    salary: 50000,
    contacts: "+799999999999",
    about: "Не улыбаюсь и пью винишко",
    status: 1,
  },
];

const exp1: workExp = {
  workStart: date,
  workEnd: date,
  companyName: "Яндекс",
  position: "Frontent-разработчик",
  resp: `Проект на Web 3.0. Разработал интерфейс администратора для работы с крипто-кошельком и смарт-контрактом. Мониторинг статистики (построение графиков), управление доступами пользователей, вывод средств, арбитражные переводы. Настроил окружение для разработки: ESLint, Prettier, Husky. Внедрил архитектуру FSD в проект, рефакторинг, код ревью, разработал UI-kit c настроенным Storybook,
  Стек: React, Typescript, React-router-dom, Wagmi, Luxon, classnames, Redux-toolkit, Vite, MetaMask , ESLint, Prettier, Husky, Storybook.

  Проект "Караоке". Построение приложения с нуля, проектирование архитектуры, сбор требований, текстовые анимации, разработка Ui кит, код ревью, улучшение качества кода коллег, настройка рабочего окружения.
  Стэк: React, Typescript, classnames, Webpack, react-use-audio-player, Zustand, ESLint, Prettier, Husky, FSD, Sass.

  Проект "Мерчант" и интефейс платежа. Построение приложения с нуля, проектирование архитектуры, сбор требований, разработка Ui кит (сложные таблицы), код ревью, наставничество, настройка рабочего окружения.
  Стэк: React, Typescript, classnames, Webpack, React-Query ESLint, Prettier, Husky, FSD, Sass.`,
};

const exp2: workExp = {
  workStart: date,
  workEnd: date,
  companyName: "Apple",
  position: "Веб-дизайнер",
  resp: `Я веб-дизайнер на Фрилансе, создаю дизайн сайтов в Figma и Adobe Photoshop , затем выполняю верстку на Тильде. Работаю в зеро блоке, настраиваю анимацию и step by step анимацию. Так же подключаю домен, выполняю базовые настройки seo`,
};

const exp3: workExp = {
  workStart: date,
  workEnd: date,
  companyName: "Google",
  position: "Веб-разработчик",
  resp: `Работа над различными проектами, в частности разработка (доработка) REST API (дополнение функционала, как результата повышение ценности продукта для заказчика), документирование кода, разработка тестов, создание микросервисов "с нуля" (проект интернет-магазина, разработка REST API, внедрение JWT) и другое.`,
};

export const applicants: applicantsList = [
  {
    firstName: "Joseph",
    lastName: "Mcguire",
    avatar: "https://source.unsplash.com/random/e07a79",
    isWinner: true,
    city: "Иркутск",
    age: 55,
    responses: 11,
    completedTestTasks: 0,
    interviews: 11,
    course: "Android-разработчик",
    graduationDate: date,
    workFormat: "Гибрид",
    grade: "Junior",
    salary: 50000,
    contacts: "+7(248)021-12-47",
    about:
      "*Быть хорошим слушателем, это в тоже время быть хорошим собеседником *Честь и понимание *Дружелюбие *Уверенность *Не безразличие *Уважение *Обратная связь",
    workExpirience: [exp1, exp2, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Savannah",
    lastName: "Nunez",
    avatar: "https://source.unsplash.com/random/c4ffad",
    isWinner: false,
    city: "Москва",
    age: 43,
    responses: 17,
    completedTestTasks: 4,
    interviews: 10,
    course: "Профессиональная вёрстка на HTML и CSS",
    graduationDate: date,
    workFormat: "Гибрид",
    grade: "Middle+",
    salary: 60000,
    contacts: "+7(296)678-47-49",
    about:
      "До 2008 я работал в сфере строительства и ремонта на различных должностях: прораб, инженер, менеджер проекта и др. В то время решил повысить свой уровень и занялся изучением систем автоматизированного проектирования (САПР). Это изучение происходило через Интернет, поэтому не могло не коснуться и изучения самих сетевых технологий. И как-то это понемногу затянуло настолько, что незаметно произошла и смена самой сферы деятельности. Занялся самообразованием, пошёл на фриланс набираться опыта и вот я в IT.",
    workExpirience: [exp3, exp1, exp2],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Julian",
    lastName: "Flynn",
    avatar: "https://source.unsplash.com/random/71f7c1",
    isWinner: true,
    city: "Владивосток",
    age: 45,
    responses: 13,
    completedTestTasks: 8,
    interviews: 2,
    course: "Инженер по тестированию",
    graduationDate: date,
    workFormat: "Полный день",
    grade: "Senior",
    salary: 45000,
    contacts: "+7(874)248-25-87",
    about:
      "Мои навыки  Языки Программирования: Python, JS, GO, Dart, C  Также: HTML, CSS, SQL  Фреймворки: FASTapi, Flask, Gorilla, Django, VueJS, Flatter (Изучаю), AIohttp, aiogram, Sanic, tornado, Nuxt JS  Библиотеки: Scrapy, Numpy, Pandas, BeautifulSoup, multiprocessing, thread, loging и др.  Опыт работы с SQL DB: -postgreSQL, mysql, SQlite  Опыт работы с Redis, RedisMQ  Опыт в написании Микросервисных приложений а также Монолитных  OS: Основная система Ubuntu, есть опыт работы со следующими дистрибутивами mint, fedora, ubuntu, ubuntu server  Дополнительно: Имеется понимание ООП и знание паттернов. Понимание асинхронного программирование  Дополнительно о сделанных проектах можете посмотреть по ссылке на гитхаб: https://github.com/chigan0",
    workExpirience: [exp2, exp1, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Hannah",
    lastName: "Dejesus",
    avatar: "https://source.unsplash.com/random/75f4a4",
    isWinner: true,
    city: "Омск",
    age: 39,
    responses: 1,
    completedTestTasks: 10,
    interviews: 8,
    course: "Профессиональная вёрстка на HTML и CSS",
    graduationDate: date,
    workFormat: "Удаленная работа",
    grade: "Senior",
    salary: 40000,
    contacts: "+7(484)199-81-93",
    about:
      "Сейчас работаю с базами данных(MSSQL, PostgreSQL, Oracle) и чутка с формами DevExpress(C#/VB) в банковской отрасли.  Учился писать на C# и работать в Unity, но рабочего опыта не имею.  Открыт для предложений. Готов рассмотреть предложения работ с базами данных, C# и/или Unity3D.",
    workExpirience: [exp2, exp3, exp1],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Brent",
    lastName: "Rollins",
    avatar: "https://source.unsplash.com/random/85f7f3",
    isWinner: false,
    city: "Ижевск",
    age: 57,
    responses: 15,
    completedTestTasks: 2,
    interviews: 12,
    course: "Фулстек-разработчик",
    graduationDate: date,
    workFormat: "Гибкий график",
    grade: "Middle",
    salary: 55000,
    contacts: "+7(505)863-06-40",
    about:
      "С вуза знаком с c++ и алгоритмами, а на работе познакомился с python, когда появилась необходимость в автоматизации и работе с большими данными. Хотел бы заниматься тем, что будет приносить деньги компании, что будет не просто полезно, но и нужно",
    workExpirience: [exp1, exp2, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Carly",
    lastName: "Williamson",
    avatar: "https://source.unsplash.com/random/54b1ea",
    isWinner: false,
    city: "Севастополь",
    age: 57,
    responses: 15,
    completedTestTasks: 7,
    interviews: 7,
    course: "Инженер по тестированию",
    graduationDate: date,
    workFormat: "Гибрид",
    grade: "Senior",
    salary: 90000,
    contacts: "+7(313)837-34-06",
    about:
      "*Быть хорошим слушателем, это в тоже время быть хорошим собеседником *Честь и понимание *Дружелюбие *Уверенность *Не безразличие *Уважение *Обратная связь",
    workExpirience: [exp3, exp1, exp2],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Oleg",
    lastName: "Kemp",
    avatar: "https://source.unsplash.com/random/0006ba",
    isWinner: false,
    city: "Казань",
    age: 44,
    responses: 5,
    completedTestTasks: 3,
    interviews: 6,
    course: "Android-разработчик",
    graduationDate: date,
    workFormat: "Удаленная работа",
    grade: "Senior",
    salary: 50000,
    contacts: "+7(424)446-40-85",
    about:
      "Навыки  - Java (Core, Collections, Multithreading, Exceptions) - Spring Framework (REST, Security, Data, Core) - SQL - JPA - Liquibase - JUnit - Maven - Git - Lombok - Thymeleaf - log4j2 - Основы ООП -Apache Kafka",
    workExpirience: [exp2, exp1, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Colt",
    lastName: "Gallegos",
    avatar: "https://source.unsplash.com/random/e59ed6",
    isWinner: false,
    city: "Севастополь",
    age: 42,
    responses: 20,
    completedTestTasks: 0,
    interviews: 16,
    course: "Основы дизайна в Figma",
    graduationDate: date,
    workFormat: "Удаленная работа",
    grade: "Junior",
    salary: 60000,
    contacts: "+7(266)315-47-27",
    about:
      "*Быть хорошим слушателем, это в тоже время быть хорошим собеседником *Честь и понимание *Дружелюбие *Уверенность *Не безразличие *Уважение *Обратная связь",
    workExpirience: [exp2, exp3, exp1],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Sara",
    lastName: "Lynch",
    avatar: "https://source.unsplash.com/random/b3aded",
    isWinner: false,
    city: "Москва",
    age: 20,
    responses: 5,
    completedTestTasks: 5,
    interviews: 8,
    course: "Основы дизайна в Figma",
    graduationDate: date,
    workFormat: "Полный день",
    grade: "Middle",
    salary: 45000,
    contacts: "+7(277)557-35-41",
    about:
      "До 2008 я работал в сфере строительства и ремонта на различных должностях: прораб, инженер, менеджер проекта и др. В то время решил повысить свой уровень и занялся изучением систем автоматизированного проектирования (САПР). Это изучение происходило через Интернет, поэтому не могло не коснуться и изучения самих сетевых технологий. И как-то это понемногу затянуло настолько, что незаметно произошла и смена самой сферы деятельности. Занялся самообразованием, пошёл на фриланс набираться опыта и вот я в IT.",
    workExpirience: [exp1, exp2, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Risa",
    lastName: "Mccormick",
    avatar: "https://source.unsplash.com/random/75abe5",
    isWinner: true,
    city: "Нижний Новгород",
    age: 40,
    responses: 18,
    completedTestTasks: 7,
    interviews: 9,
    course: "Аналитик данных",
    graduationDate: date,
    workFormat: "Удаленная работа",
    grade: "Middle+",
    salary: 40000,
    contacts: "+7(773)775-30-81",
    about:
      "Пишу картины, занимаюсь оформлением свадьб, изготовлением декоративной и сувенирной продукции любого типа. Активная, коммуникабельная, творческая, быстро обучаюсь, есть опыт работы в команде, быстро привыкаю к новой обстановке и легко вливаюсь в новый коллектив.",
    workExpirience: [exp3, exp1, exp2],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Amela",
    lastName: "Henderson",
    avatar: "https://source.unsplash.com/random/98aaf2",
    isWinner: false,
    city: "Краснодар",
    age: 49,
    responses: 22,
    completedTestTasks: 9,
    interviews: 5,
    course: "Основы математики для цифровых профессий",
    graduationDate: date,
    workFormat: "Гибрид",
    grade: "Senior",
    salary: 55000,
    contacts: "+7(984)842-75-84",
    about:
      "Ищу работу Frontend-разработчиком.  Пишу на JS, знаю ReactJs, Python Ранее выполнял такие работы как: Вёрстка по макетам Figma Написание сайтов со стаком MERN Переписание Ui на PHP Создание и поддержание проектов    Ключевые навыки: -Javasript ES6 - HTML5 - CSS3 (sass, less) - React.js / Redux - Node.js - Gulp / Webpack - Docker -Python Сертификаты: - HTML/CSS, JavaScript, React.",
    workExpirience: [exp2, exp1, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Camilla",
    lastName: "Whitehead",
    avatar: "https://source.unsplash.com/random/b894dd",
    isWinner: false,
    city: "Воронеж",
    age: 49,
    responses: 11,
    completedTestTasks: 0,
    interviews: 5,
    course: "Аналитик данных",
    graduationDate: date,
    workFormat: "Гибкий график",
    grade: "Middle+",
    salary: 90000,
    contacts: "+7(448)087-11-18",
    about:
      "Общителен, обучаем, пользуюсь авторитетом у коллег. Мое хобби - системы видеонаблюдения. Женат, дочь - 10 лет",
    workExpirience: [exp2, exp3, exp1],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Kelsie",
    lastName: "James",
    avatar: "https://source.unsplash.com/random/82ea52",
    isWinner: false,
    city: "Владивосток",
    age: 48,
    responses: 13,
    completedTestTasks: 3,
    interviews: 14,
    course: "Инженер по тестированию",
    graduationDate: date,
    workFormat: "Гибкий график",
    grade: "Middle+",
    salary: 50000,
    contacts: "+7(686)961-44-62",
    about:
      "J2SE, J2EE, JSP, JSF, JDBC, AJAX, HTML, JavaScript, CSS PL/SQL (Oracle 8,9i,10,11) Java AppSer: Resin.TomCat, GlassFish server. ПО: NetBeans IDE, PL/SQL Developer.",
    workExpirience: [exp1, exp2, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Hyatt",
    lastName: "Levine",
    avatar: "https://source.unsplash.com/random/101d6b",
    isWinner: false,
    city: "Нижний Новгород",
    age: 20,
    responses: 14,
    completedTestTasks: 7,
    interviews: 16,
    course: "Android-разработчик",
    graduationDate: date,
    workFormat: "Гибкий график",
    grade: "Senior",
    salary: 60000,
    contacts: "+7(971)181-76-14",
    about:
      "Навыки  - Java (Core, Collections, Multithreading, Exceptions) - Spring Framework (REST, Security, Data, Core) - SQL - JPA - Liquibase - JUnit - Maven - Git - Lombok - Thymeleaf - log4j2 - Основы ООП -Apache Kafka",
    workExpirience: [exp3, exp1, exp2],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Gary",
    lastName: "Jordan",
    avatar: "https://source.unsplash.com/random/1cb25b",
    isWinner: false,
    city: "Тольятти",
    age: 51,
    responses: 16,
    completedTestTasks: 5,
    interviews: 9,
    course: "Курсы английского для работы в IT",
    graduationDate: date,
    workFormat: "Полный день",
    grade: "Junior",
    salary: 45000,
    contacts: "+7(400)379-25-44",
    about:
      "- automated trading strategies development in Scala/C+ - data mining development for Amazon cloud (Linux/Windows), Java/Scala - Lighspeed Gateway & Market Data servers protocol depth knowledge - NASDAQ & NYSE markets depth understanding",
    workExpirience: [exp2, exp1, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Orlando",
    lastName: "Barton",
    avatar: "https://source.unsplash.com/random/9e44dd",
    isWinner: false,
    city: "Уфа",
    age: 30,
    responses: 15,
    completedTestTasks: 9,
    interviews: 21,
    course: "Фронтенд-разработчик",
    graduationDate: date,
    workFormat: "Удаленная работа",
    grade: "Middle+",
    salary: 40000,
    contacts: "+7(511)257-17-32",
    about:
      "До 2008 я работал в сфере строительства и ремонта на различных должностях: прораб, инженер, менеджер проекта и др. В то время решил повысить свой уровень и занялся изучением систем автоматизированного проектирования (САПР). Это изучение происходило через Интернет, поэтому не могло не коснуться и изучения самих сетевых технологий. И как-то это понемногу затянуло настолько, что незаметно произошла и смена самой сферы деятельности. Занялся самообразованием, пошёл на фриланс набираться опыта и вот я в IT.",
    workExpirience: [exp2, exp3, exp1],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Stephen",
    lastName: "Mclaughlin",
    avatar: "https://source.unsplash.com/random/bf991c",
    isWinner: false,
    city: "Севастополь",
    age: 49,
    responses: 18,
    completedTestTasks: 10,
    interviews: 22,
    course: "React-разработчик",
    graduationDate: date,
    workFormat: "Полный день",
    grade: "Middle",
    salary: 55000,
    contacts: "+7(250)026-04-17",
    about:
      "Профессиональный подход к работе, быстрое выполнение заданий, креативное мышление",
    workExpirience: [exp1, exp2, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Bryar",
    lastName: "Pittman",
    avatar: "https://source.unsplash.com/random/b7e079",
    isWinner: true,
    city: "Тольятти",
    age: 42,
    responses: 17,
    completedTestTasks: 6,
    interviews: 19,
    course: "Основы работы с Git",
    graduationDate: date,
    workFormat: "Гибкий график",
    grade: "Senior",
    salary: 90000,
    contacts: "+7(322)118-77-48",
    about:
      "Мои навыки  Языки Программирования: Python, JS, GO, Dart, C  Также: HTML, CSS, SQL  Фреймворки: FASTapi, Flask, Gorilla, Django, VueJS, Flatter (Изучаю), AIohttp, aiogram, Sanic, tornado, Nuxt JS  Библиотеки: Scrapy, Numpy, Pandas, BeautifulSoup, multiprocessing, thread, loging и др.  Опыт работы с SQL DB: -postgreSQL, mysql, SQlite  Опыт работы с Redis, RedisMQ  Опыт в написании Микросервисных приложений а также Монолитных  OS: Основная система Ubuntu, есть опыт работы со следующими дистрибутивами mint, fedora, ubuntu, ubuntu server  Дополнительно: Имеется понимание ООП и знание паттернов. Понимание асинхронного программирование  Дополнительно о сделанных проектах можете посмотреть по ссылке на гитхаб: https://github.com/chigan0",
    workExpirience: [exp3, exp1, exp2],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Baxter",
    lastName: "Irwin",
    avatar: "https://source.unsplash.com/random/0c9e0c",
    isWinner: true,
    city: "Томск",
    age: 38,
    responses: 0,
    completedTestTasks: 9,
    interviews: 18,
    course: "Разработчик 1C",
    graduationDate: date,
    workFormat: "Удаленная работа",
    grade: "Middle",
    salary: 50000,
    contacts: "+7(830)362-10-65",
    about:
      "Мои навыки  Языки Программирования: Python, JS, GO, Dart, C  Также: HTML, CSS, SQL  Фреймворки: FASTapi, Flask, Gorilla, Django, VueJS, Flatter (Изучаю), AIohttp, aiogram, Sanic, tornado, Nuxt JS  Библиотеки: Scrapy, Numpy, Pandas, BeautifulSoup, multiprocessing, thread, loging и др.  Опыт работы с SQL DB: -postgreSQL, mysql, SQlite  Опыт работы с Redis, RedisMQ  Опыт в написании Микросервисных приложений а также Монолитных  OS: Основная система Ubuntu, есть опыт работы со следующими дистрибутивами mint, fedora, ubuntu, ubuntu server  Дополнительно: Имеется понимание ООП и знание паттернов. Понимание асинхронного программирование  Дополнительно о сделанных проектах можете посмотреть по ссылке на гитхаб: https://github.com/chigan0",
    workExpirience: [exp2, exp1, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Brianna",
    lastName: "Little",
    avatar: "https://source.unsplash.com/random/aefcd4",
    isWinner: true,
    city: "Томск",
    age: 29,
    responses: 1,
    completedTestTasks: 7,
    interviews: 23,
    course: "Продуктовый подход для дизайнеров",
    graduationDate: date,
    workFormat: "Удаленная работа",
    grade: "Junior",
    salary: 60000,
    contacts: "+7(759)486-22-26",
    about:
      "Основной язык разработки C++17. Опыт написания программ на C#, python. Опыт работы с протоколами: usb, rs232, rs485, modbus, tcp, udp, spi, i2c. Опыт работы с freertos. Опыт работы с микроконтроллерами stm32f1, stm32f4, nuvoton m051. Навыки кросс-платформенной разработки. Небольшой опыт работы с qt. Небольшой опыт работы с Xamarin.Forms.",
    workExpirience: [exp2, exp3, exp1],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Cain",
    lastName: "Meyer",
    avatar: "https://source.unsplash.com/random/c0bfff",
    isWinner: false,
    city: "Томск",
    age: 33,
    responses: 3,
    completedTestTasks: 1,
    interviews: 4,
    course: "Аналитик данных",
    graduationDate: date,
    workFormat: "Удаленная работа",
    grade: "Senior",
    salary: 45000,
    contacts: "+7(546)419-83-61",
    about:
      "- automated trading strategies development in Scala/C+ - data mining development for Amazon cloud (Linux/Windows), Java/Scala - Lighspeed Gateway & Market Data servers protocol depth knowledge - NASDAQ & NYSE markets depth understanding",
    workExpirience: [exp1, exp2, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Xander",
    lastName: "Rich",
    avatar: "https://source.unsplash.com/random/eff44e",
    isWinner: false,
    city: "Казань",
    age: 21,
    responses: 8,
    completedTestTasks: 8,
    interviews: 11,
    course: "Android-разработчик",
    graduationDate: date,
    workFormat: "Гибкий график",
    grade: "Senior",
    salary: 40000,
    contacts: "+7(963)458-06-57",
    about:
      "Учась в Университете, увлекался программированием с 1991 года. Закончил Аспирантуру. Писал диссертацию. Профессионально занимаюсь IT последние 26 лет (подтверждённый трудовой стаж с 1994 года). Первые 15 лет как IT специалист разных компаний с самым широким кругом задач по обеспечению работы компаний. Последние 10 лет, занимаюсь ведением собственного IT бизнеса в области телекоммуникаций.",
    workExpirience: [exp3, exp1, exp2],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Yoko",
    lastName: "Cherry",
    avatar: "https://source.unsplash.com/random/c2d35f",
    isWinner: false,
    city: "Казань",
    age: 45,
    responses: 14,
    completedTestTasks: 1,
    interviews: 21,
    course: "Основы работы с Git",
    graduationDate: date,
    workFormat: "Удаленная работа",
    grade: "Senior",
    salary: 55000,
    contacts: "+7(278)237-25-65",
    about:
      "Ищу работу Frontend-разработчиком.  Пишу на JS, знаю ReactJs, Python Ранее выполнял такие работы как: Вёрстка по макетам Figma Написание сайтов со стаком MERN Переписание Ui на PHP Создание и поддержание проектов    Ключевые навыки: -Javasript ES6 - HTML5 - CSS3 (sass, less) - React.js / Redux - Node.js - Gulp / Webpack - Docker -Python Сертификаты: - HTML/CSS, JavaScript, React.",
    workExpirience: [exp2, exp1, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Baker",
    lastName: "Carter",
    avatar: "https://source.unsplash.com/random/3cc489",
    isWinner: true,
    city: "Владивосток",
    age: 54,
    responses: 2,
    completedTestTasks: 9,
    interviews: 12,
    course: "Android-разработчик",
    graduationDate: date,
    workFormat: "Гибкий график",
    grade: "Middle",
    salary: 90000,
    contacts: "+7(266)231-73-77",
    about:
      "Личные навыки: Имею желание развиваться и работать, нацелен на результат. Спокоен, вежлив, грамотная речь. Компьютерные навыки: Владение Microsoft Office, LabView, Multisim, Matlab + Simulink Профессиональные интересы: Организация локальных вычислительных сетей, создание виртуальных приборов и систем сборов данных с использованием National Instruments LabVIEW, моделирование и расчеты с использованием Matlab/Simulink.",
    workExpirience: [exp2, exp3, exp1],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Melvin",
    lastName: "Velasquez",
    avatar: "https://source.unsplash.com/random/ec92f4",
    isWinner: true,
    city: "Омск",
    age: 55,
    responses: 13,
    completedTestTasks: 0,
    interviews: 12,
    course: "Аналитик данных",
    graduationDate: date,
    workFormat: "Удаленная работа",
    grade: "Middle",
    salary: 50000,
    contacts: "+7(137)374-07-35",
    about:
      "Пишу картины, занимаюсь оформлением свадьб, изготовлением декоративной и сувенирной продукции любого типа. Активная, коммуникабельная, творческая, быстро обучаюсь, есть опыт работы в команде, быстро привыкаю к новой обстановке и легко вливаюсь в новый коллектив.",
    workExpirience: [exp1, exp2, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Evan",
    lastName: "Farmer",
    avatar: "https://source.unsplash.com/random/c7d108",
    isWinner: true,
    city: "Нижний Новгород",
    age: 23,
    responses: 11,
    completedTestTasks: 3,
    interviews: 16,
    course: "React-разработчик",
    graduationDate: date,
    workFormat: "Гибкий график",
    grade: "Junior",
    salary: 60000,
    contacts: "+7(779)694-17-17",
    about:
      "Личные навыки: Имею желание развиваться и работать, нацелен на результат. Спокоен, вежлив, грамотная речь. Компьютерные навыки: Владение Microsoft Office, LabView, Multisim, Matlab + Simulink Профессиональные интересы: Организация локальных вычислительных сетей, создание виртуальных приборов и систем сборов данных с использованием National Instruments LabVIEW, моделирование и расчеты с использованием Matlab/Simulink.",
    workExpirience: [exp3, exp1, exp2],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Preston",
    lastName: "Nunez",
    avatar: "https://source.unsplash.com/random/bb1df4",
    isWinner: false,
    city: "Москва",
    age: 52,
    responses: 10,
    completedTestTasks: 7,
    interviews: 8,
    course: "Инженер по тестированию",
    graduationDate: date,
    workFormat: "Гибрид",
    grade: "Junior",
    salary: 45000,
    contacts: "+7(202)177-54-40",
    about:
      "Навыки  - Java (Core, Collections, Multithreading, Exceptions) - Spring Framework (REST, Security, Data, Core) - SQL - JPA - Liquibase - JUnit - Maven - Git - Lombok - Thymeleaf - log4j2 - Основы ООП -Apache Kafka",
    workExpirience: [exp2, exp1, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Adam",
    lastName: "Berger",
    avatar: "https://source.unsplash.com/random/b907f9",
    isWinner: true,
    city: "Екатеринбург",
    age: 46,
    responses: 21,
    completedTestTasks: 8,
    interviews: 13,
    course: "Разработчик 1C",
    graduationDate: date,
    workFormat: "Удаленная работа",
    grade: "Middle+",
    salary: 40000,
    contacts: "+7(184)040-52-25",
    about:
      "С вуза знаком с c++ и алгоритмами, а на работе познакомился с python, когда появилась необходимость в автоматизации и работе с большими данными. Хотел бы заниматься тем, что будет приносить деньги компании, что будет не просто полезно, но и нужно",
    workExpirience: [exp2, exp3, exp1],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Donna",
    lastName: "Villarreal",
    avatar: "https://source.unsplash.com/random/9c99f7",
    isWinner: false,
    city: "Тюмень",
    age: 20,
    responses: 3,
    completedTestTasks: 5,
    interviews: 22,
    course: "Основы работы с Git",
    graduationDate: date,
    workFormat: "Гибрид",
    grade: "Junior",
    salary: 55000,
    contacts: "+7(502)919-02-14",
    about:
      "Опыт на стеке Net Core, ASP.NET Core, WebAPI ASP.NET Core, Identity ASP.NET Core, JWT, Blazor, MVC, Entity Framework Core, RabbitMQ, NUnit, CQRS, AutoMapper.  PostgreSQL, MS SQL, Git, GitLab, Docker, Visual Studio, Jira, Redmine.  Следую принципам YAGNI, DRY, KISS, SOLID.  Опыт работы в командах до сорока участников. Создаю надёжный, читаемый и документированный код.",
    workExpirience: [exp1, exp2, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Teagan",
    lastName: "Mccullough",
    avatar: "https://source.unsplash.com/random/f725a6",
    isWinner: true,
    city: "Ростов-на-Дону",
    age: 41,
    responses: 0,
    completedTestTasks: 7,
    interviews: 15,
    course: "Бэкенд на Node.js для фронтенд-разработчиков",
    graduationDate: date,
    workFormat: "Удаленная работа",
    grade: "Junior",
    salary: 90000,
    contacts: "+7(713)631-23-37",
    about:
      "J2SE, J2EE, JSP, JSF, JDBC, AJAX, HTML, JavaScript, CSS PL/SQL (Oracle 8,9i,10,11) Java AppSer: Resin.TomCat, GlassFish server. ПО: NetBeans IDE, PL/SQL Developer.",
    workExpirience: [exp3, exp1, exp2],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Donovan",
    lastName: "Potts",
    avatar: "https://source.unsplash.com/random/f9c0e1",
    isWinner: false,
    city: "Челябинск",
    age: 28,
    responses: 12,
    completedTestTasks: 8,
    interviews: 9,
    course: "Основы математики для цифровых профессий",
    graduationDate: date,
    workFormat: "Гибкий график",
    grade: "Junior",
    salary: 50000,
    contacts: "+7(772)713-72-50",
    about:
      "Сейчас работаю с базами данных(MSSQL, PostgreSQL, Oracle) и чутка с формами DevExpress(C#/VB) в банковской отрасли.  Учился писать на C# и работать в Unity, но рабочего опыта не имею.  Открыт для предложений. Готов рассмотреть предложения работ с базами данных, C# и/или Unity3D.",
    workExpirience: [exp2, exp1, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Avram",
    lastName: "Gill",
    avatar: "https://source.unsplash.com/random/b3f5f9",
    isWinner: false,
    city: "Омск",
    age: 33,
    responses: 4,
    completedTestTasks: 1,
    interviews: 9,
    course: "Основы дизайна в Figma",
    graduationDate: date,
    workFormat: "Гибрид",
    grade: "Senior",
    salary: 60000,
    contacts: "+7(879)245-45-43",
    about:
      "Уверенный пользователь ПК, Corel Draw, Adobe Photoshop. Наличие деловых связей в области рекламы, умение работать в условиях быстроменяющихся задач, нацеленность на выполнение поставленных задач, возможность нахождения в коротких командировках, высокая корпоративная лояльность, умение работать в команде, исполнительность, способность к самостоятельным решениям, ответственность и коммуникабельность, умение разбираться в людях, стрессоустойчивость, креативность и огромный творческий потенциал. Портфолио https://www.fl.ru/users/natiavdeeva/ и https://vk.com/nat_avdeeva",
    workExpirience: [exp2, exp3, exp1],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Craig",
    lastName: "Stout",
    avatar: "https://source.unsplash.com/random/d65ec8",
    isWinner: false,
    city: "Ижевск",
    age: 43,
    responses: 9,
    completedTestTasks: 6,
    interviews: 9,
    course: "Курсы английского для работы в IT",
    graduationDate: date,
    workFormat: "Гибрид",
    grade: "Middle+",
    salary: 45000,
    contacts: "+7(213)837-58-84",
    about:
      "С вуза знаком с c++ и алгоритмами, а на работе познакомился с python, когда появилась необходимость в автоматизации и работе с большими данными. Хотел бы заниматься тем, что будет приносить деньги компании, что будет не просто полезно, но и нужно",
    workExpirience: [exp1, exp2, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Nina",
    lastName: "Shannon",
    avatar: "https://source.unsplash.com/random/2be579",
    isWinner: true,
    city: "Екатеринбург",
    age: 28,
    responses: 2,
    completedTestTasks: 6,
    interviews: 22,
    course: "Специалист по Data Science",
    graduationDate: date,
    workFormat: "Гибрид",
    grade: "Middle+",
    salary: 40000,
    contacts: "+7(410)205-83-36",
    about:
      "Знание языков программирования. C++, Rust, C, Python.  - Победитель Международной олимпиады молодежи по математике 2018 г. - Бронзовая медаль на Евразийской олимпиаде по программированию 2017 г. - Бронзовая медаль на Республиканской олимпиаде по информатике 2017 г. - Абсолютный победитель Международной Сатпаевской олимпиады по информатике 2014 г. - Второе место Международной Сатпаевской олимпиады по информатике 2013 г.  Поедитель и призер множества других олимпиад.  Дополнительное образование: - Летняя компьютерная школа (ЛКШ) Параллель C' 2014 г. - Летний компьютерный лагерь (ЛКЛ) Параллель B' 2015 г. - Летний компьютерный лагерь (ЛКЛ) Параллель A' 2016 г. - Летний компьютерный лагерь (ЛКЛ) Параллель A 2017 г.",
    workExpirience: [exp3, exp1, exp2],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Kenneth",
    lastName: "Roth",
    avatar: "https://source.unsplash.com/random/c49329",
    isWinner: true,
    city: "Краснодар",
    age: 20,
    responses: 5,
    completedTestTasks: 7,
    interviews: 13,
    course: "Фронтенд-разработчик",
    graduationDate: date,
    workFormat: "Полный день",
    grade: "Middle+",
    salary: 55000,
    contacts: "+7(591)251-11-78",
    about:
      "Мои навыки  Языки Программирования: Python, JS, GO, Dart, C  Также: HTML, CSS, SQL  Фреймворки: FASTapi, Flask, Gorilla, Django, VueJS, Flatter (Изучаю), AIohttp, aiogram, Sanic, tornado, Nuxt JS  Библиотеки: Scrapy, Numpy, Pandas, BeautifulSoup, multiprocessing, thread, loging и др.  Опыт работы с SQL DB: -postgreSQL, mysql, SQlite  Опыт работы с Redis, RedisMQ  Опыт в написании Микросервисных приложений а также Монолитных  OS: Основная система Ubuntu, есть опыт работы со следующими дистрибутивами mint, fedora, ubuntu, ubuntu server  Дополнительно: Имеется понимание ООП и знание паттернов. Понимание асинхронного программирование  Дополнительно о сделанных проектах можете посмотреть по ссылке на гитхаб: https://github.com/chigan0",
    workExpirience: [exp2, exp1, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Leonard",
    lastName: "Atkins",
    avatar: "https://source.unsplash.com/random/55e055",
    isWinner: true,
    city: "Севастополь",
    age: 50,
    responses: 14,
    completedTestTasks: 2,
    interviews: 18,
    course: "Аналитик данных",
    graduationDate: date,
    workFormat: "Гибкий график",
    grade: "Junior",
    salary: 90000,
    contacts: "+7(267)668-63-14",
    about:
      "Личные навыки: Имею желание развиваться и работать, нацелен на результат. Спокоен, вежлив, грамотная речь. Компьютерные навыки: Владение Microsoft Office, LabView, Multisim, Matlab + Simulink Профессиональные интересы: Организация локальных вычислительных сетей, создание виртуальных приборов и систем сборов данных с использованием National Instruments LabVIEW, моделирование и расчеты с использованием Matlab/Simulink.",
    workExpirience: [exp2, exp3, exp1],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Jermaine",
    lastName: "Daugherty",
    avatar: "https://source.unsplash.com/random/8846ba",
    isWinner: false,
    city: "Новосибирск",
    age: 29,
    responses: 13,
    completedTestTasks: 8,
    interviews: 18,
    course: "Бэкенд на Node.js для фронтенд-разработчиков",
    graduationDate: date,
    workFormat: "Гибкий график",
    grade: "Middle",
    salary: 50000,
    contacts: "+7(682)424-08-03",
    about:
      "Профессиональный подход к работе, быстрое выполнение заданий, креативное мышление",
    workExpirience: [exp1, exp2, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Keiko",
    lastName: "Gibson",
    avatar: "https://source.unsplash.com/random/dd85d4",
    isWinner: false,
    city: "Воронеж",
    age: 57,
    responses: 14,
    completedTestTasks: 7,
    interviews: 7,
    course: "Основы дизайна в Adobe Photoshop",
    graduationDate: date,
    workFormat: "Гибрид",
    grade: "Junior",
    salary: 60000,
    contacts: "+7(031)341-52-47",
    about:
      "Пишу картины, занимаюсь оформлением свадьб, изготовлением декоративной и сувенирной продукции любого типа. Активная, коммуникабельная, творческая, быстро обучаюсь, есть опыт работы в команде, быстро привыкаю к новой обстановке и легко вливаюсь в новый коллектив.",
    workExpirience: [exp3, exp1, exp2],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Quin",
    lastName: "Koch",
    avatar: "https://source.unsplash.com/random/90b8db",
    isWinner: true,
    city: "Волгоград",
    age: 46,
    responses: 11,
    completedTestTasks: 3,
    interviews: 14,
    course: "Инженер по тестированию",
    graduationDate: date,
    workFormat: "Удаленная работа",
    grade: "Middle+",
    salary: 45000,
    contacts: "+7(803)648-46-68",
    about:
      "- automated trading strategies development in Scala/C+ - data mining development for Amazon cloud (Linux/Windows), Java/Scala - Lighspeed Gateway & Market Data servers protocol depth knowledge - NASDAQ & NYSE markets depth understanding",
    workExpirience: [exp2, exp1, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Mannix",
    lastName: "Boyd",
    avatar: "https://source.unsplash.com/random/30c1ff",
    isWinner: false,
    city: "Тольятти",
    age: 49,
    responses: 4,
    completedTestTasks: 3,
    interviews: 21,
    course: "Профессиональная вёрстка на HTML и CSS",
    graduationDate: date,
    workFormat: "Гибрид",
    grade: "Middle",
    salary: 40000,
    contacts: "+7(888)224-41-69",
    about:
      "Профессиональные навыки: -Опыт использования Linux систем; -Администрирование локальных сетей; -Хорошее знание компьютерных комплектующих; -Определение неполадок и дальнейший ремонт компьютеров, оргтехники; -Настройка и установка СКС; -Настройка активного сетевого оборудования; -Обучение пользователей; -Решение любых проблем с пользовательским ПО; -Системы видеонаблюдения;  Личные качества: - Аналитический склад ума; - Обучаемость; - Трудолюбие; - Ответственность; - Стрессоустойчивость; - Неуязвимость; - Коммуникабельность; - Способность к принятию нестандартных решений. - Навыки ремонта цифровой техники.",
    workExpirience: [exp2, exp3, exp1],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Acton",
    lastName: "Valenzuela",
    avatar: "https://source.unsplash.com/random/f279e6",
    isWinner: true,
    city: "Краснодар",
    age: 58,
    responses: 8,
    completedTestTasks: 0,
    interviews: 15,
    course: "Продуктовый подход для дизайнеров",
    graduationDate: date,
    workFormat: "Гибрид",
    grade: "Senior",
    salary: 55000,
    contacts: "+7(569)187-86-62",
    about:
      "Учась в Университете, увлекался программированием с 1991 года. Закончил Аспирантуру. Писал диссертацию. Профессионально занимаюсь IT последние 26 лет (подтверждённый трудовой стаж с 1994 года). Первые 15 лет как IT специалист разных компаний с самым широким кругом задач по обеспечению работы компаний. Последние 10 лет, занимаюсь ведением собственного IT бизнеса в области телекоммуникаций.",
    workExpirience: [exp1, exp2, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Bradley",
    lastName: "Diaz",
    avatar: "https://source.unsplash.com/random/e6fca6",
    isWinner: false,
    city: "Воронеж",
    age: 32,
    responses: 14,
    completedTestTasks: 7,
    interviews: 8,
    course: "Python-разработчик плюс",
    graduationDate: date,
    workFormat: "Гибрид",
    grade: "Middle+",
    salary: 90000,
    contacts: "+7(726)386-46-21",
    about:
      "Профессиональные навыки: - Уверенный пользователь ПК; - Знание пакета CorelDraw; - Грамотность речи и письма; - Творческий подход в работе;  Личные качества: Исполнительность, коммуникабельность, креативность, чувство стиля, богатое воображение, усидчивость, готовность к работе в интенсивном режиме, аккуратность, адаптивность, самостоятельность.  Дополнительные сведения: Семейное положение: не замужем.",
    workExpirience: [exp3, exp1, exp2],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "John",
    lastName: "Farrell",
    avatar: "https://source.unsplash.com/random/51d1a4",
    isWinner: true,
    city: "Иркутск",
    age: 56,
    responses: 3,
    completedTestTasks: 10,
    interviews: 22,
    course: "Разработчик 1C",
    graduationDate: date,
    workFormat: "Удаленная работа",
    grade: "Senior",
    salary: 50000,
    contacts: "+7(574)725-25-83",
    about:
      "Профессиональные навыки: - Уверенный пользователь ПК; - Знание пакета CorelDraw; - Грамотность речи и письма; - Творческий подход в работе;  Личные качества: Исполнительность, коммуникабельность, креативность, чувство стиля, богатое воображение, усидчивость, готовность к работе в интенсивном режиме, аккуратность, адаптивность, самостоятельность.  Дополнительные сведения: Семейное положение: не замужем.",
    workExpirience: [exp2, exp1, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Rebekah",
    lastName: "Cotton",
    avatar: "https://source.unsplash.com/random/f94daf",
    isWinner: false,
    city: "Пермь",
    age: 37,
    responses: 10,
    completedTestTasks: 6,
    interviews: 18,
    course: "SMM- и контент-маркетолог",
    graduationDate: date,
    workFormat: "Полный день",
    grade: "Senior",
    salary: 60000,
    contacts: "+7(763)415-31-27",
    about:
      "Навыки  - Java (Core, Collections, Multithreading, Exceptions) - Spring Framework (REST, Security, Data, Core) - SQL - JPA - Liquibase - JUnit - Maven - Git - Lombok - Thymeleaf - log4j2 - Основы ООП -Apache Kafka",
    workExpirience: [exp2, exp3, exp1],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Medge",
    lastName: "Reid",
    avatar: "https://source.unsplash.com/random/d216e0",
    isWinner: true,
    city: "Екатеринбург",
    age: 56,
    responses: 12,
    completedTestTasks: 7,
    interviews: 9,
    course: "Основы работы с Git",
    graduationDate: date,
    workFormat: "Удаленная работа",
    grade: "Middle",
    salary: 45000,
    contacts: "+7(270)753-81-67",
    about:
      "Справляюсь со сложными задачами, ответственно и креативно отношусь к работе. Быстро и с удовольствием учусь, хорошо работаю в команде.  Проявляю интерес к технологиям и науке. Реализовала несколько мини-проектов: 1) Задача о распространении тепла. - Разработала линейный программный код C++ для решения уравнения теплопроводности с заданными исходными данными; - Применила технологию распараллеливания с помощью стандарта MPI с последующим запуском на кластере. Инструменты: C++, MPI, Tecplot, численные методы, Git, математическая физика. 2) Клиент-серверное приложение. - Разработала прототип клиент-серверного приложения для записи информации о пользователях в базу данных. Инструменты: Python, Sqlite, Socket.  В школьные годы активно участвовала в профильных олимпиадах по физике/математике. В 10-11 классе разработала устройство для ориентирования слепых и слабовидящих людей. Принимала участие в конкурсе Intel Isef 2019 в США.  Участвую в проектных конкурсах в качестве члена молодежного жюри (ЮНИОР, Балтийский научно-инженерный конкурс).  Хобби: скалолазание, бег, пляжный волейбол, лыжи, кофеология.",
    workExpirience: [exp1, exp2, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Laith",
    lastName: "Davis",
    avatar: "https://source.unsplash.com/random/fff7b2",
    isWinner: true,
    city: "Самара",
    age: 46,
    responses: 6,
    completedTestTasks: 3,
    interviews: 5,
    course: "Дизайнер интерфейсов",
    graduationDate: date,
    workFormat: "Гибрид",
    grade: "Middle",
    salary: 40000,
    contacts: "+7(353)658-42-32",
    about:
      "С вуза знаком с c++ и алгоритмами, а на работе познакомился с python, когда появилась необходимость в автоматизации и работе с большими данными. Хотел бы заниматься тем, что будет приносить деньги компании, что будет не просто полезно, но и нужно",
    workExpirience: [exp3, exp1, exp2],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Barbara",
    lastName: "Carney",
    avatar: "https://source.unsplash.com/random/5fd885",
    isWinner: false,
    city: "Екатеринбург",
    age: 39,
    responses: 10,
    completedTestTasks: 2,
    interviews: 4,
    course: "Дизайнер интерфейсов",
    graduationDate: date,
    workFormat: "Полный день",
    grade: "Senior",
    salary: 55000,
    contacts: "+7(984)641-76-23",
    about:
      "- automated trading strategies development in Scala/C+ - data mining development for Amazon cloud (Linux/Windows), Java/Scala - Lighspeed Gateway & Market Data servers protocol depth knowledge - NASDAQ & NYSE markets depth understanding",
    workExpirience: [exp2, exp1, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Carlos",
    lastName: "Middleton",
    avatar: "https://source.unsplash.com/random/42f22b",
    isWinner: false,
    city: "Волгоград",
    age: 39,
    responses: 6,
    completedTestTasks: 1,
    interviews: 19,
    course: "React-разработчик",
    graduationDate: date,
    workFormat: "Гибкий график",
    grade: "Junior",
    salary: 90000,
    contacts: "+7(884)491-08-86",
    about:
      "J2SE, J2EE, JSP, JSF, JDBC, AJAX, HTML, JavaScript, CSS PL/SQL (Oracle 8,9i,10,11) Java AppSer: Resin.TomCat, GlassFish server. ПО: NetBeans IDE, PL/SQL Developer.",
    workExpirience: [exp2, exp3, exp1],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Sade",
    lastName: "Patterson",
    avatar: "https://source.unsplash.com/random/6e22f9",
    isWinner: true,
    city: "Омск",
    age: 50,
    responses: 11,
    completedTestTasks: 0,
    interviews: 21,
    course: "Курсы английского для работы в IT",
    graduationDate: date,
    workFormat: "Удаленная работа",
    grade: "Junior",
    salary: 50000,
    contacts: "+7(121)281-45-15",
    about:
      "Профессиональные навыки: -Опыт использования Linux систем; -Администрирование локальных сетей; -Хорошее знание компьютерных комплектующих; -Определение неполадок и дальнейший ремонт компьютеров, оргтехники; -Настройка и установка СКС; -Настройка активного сетевого оборудования; -Обучение пользователей; -Решение любых проблем с пользовательским ПО; -Системы видеонаблюдения;  Личные качества: - Аналитический склад ума; - Обучаемость; - Трудолюбие; - Ответственность; - Стрессоустойчивость; - Неуязвимость; - Коммуникабельность; - Способность к принятию нестандартных решений. - Навыки ремонта цифровой техники.",
    workExpirience: [exp1, exp2, exp3],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
  {
    firstName: "Shaine",
    lastName: "Gamble",
    avatar: "https://source.unsplash.com/random/c96744",
    isWinner: true,
    city: "Челябинск",
    age: 27,
    responses: 15,
    completedTestTasks: 1,
    interviews: 4,
    course: "Основы математики для цифровых профессий",
    graduationDate: date,
    workFormat: "Гибкий график",
    grade: "Senior",
    salary: 60000,
    contacts: "+7(183)337-01-72",
    about:
      "Опыт на стеке Net Core, ASP.NET Core, WebAPI ASP.NET Core, Identity ASP.NET Core, JWT, Blazor, MVC, Entity Framework Core, RabbitMQ, NUnit, CQRS, AutoMapper.  PostgreSQL, MS SQL, Git, GitLab, Docker, Visual Studio, Jira, Redmine.  Следую принципам YAGNI, DRY, KISS, SOLID.  Опыт работы в командах до сорока участников. Создаю надёжный, читаемый и документированный код.",
    workExpirience: [exp3, exp1, exp2],
    studyingStatus: "Студент",
    workStatus: "Около-релевантный",
    responseStatus: "Отклик",
  },
];
